### ISSUE TITLE
Turn bluetooth on/off. Feature request

### ISSUE THREAD

**Issue by supiiik** [syssi/esphome-jk-bms#102]
Hi, can you please add a swith to enable/disable bluetooth on ESP32? It would be great to have this option, so I can temporarily connect JK-BMS with my phone and it's not need to power off the ESP32 because of that.
Thank you.

**Comment by syssi** [comment]
Good idea! I will have a look how achieve this goal.

**Comment by syssi** [comment]
Please extend your config yaml by a BLE Client switch and give it a try: https://github.com/syssi/esphome-jk-bms/pull/103/files

https://esphome.io/components/switch/ble_client.html

Could you report your success here? I didn't test the solution but I'm pretty sure it should work.

**Comment by supiiik** [comment]
It's working. Thanks :)
