### ISSUE TITLE
Add JK-BD6A20S10P as supported via BLE

### ISSUE THREAD

**Issue by adadrag** [syssi/esphome-jk-bms#123]
Dear support,

Just to let you know that I tested the Bluetooth version of JK-BD6A20S10P and it is working fine with an ESP32Dev version.
I just had to replace my Bluetooth MAC address and it is all working.

Keep up the good work!

**Comment by syssi** [comment]
Thanks for your feedback! Could you provide the software and hardware version of your BMS?
