### ISSUE TITLE
You are mentioned in official manual!

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [syssi/esphome-jk-bms#132]
Hello!

I just received my JK BMS and your repo was mentioned in official manual. I'd like to congratulate you! 🎉

![IMG_20220630_115219.jpg](https://user-images.githubusercontent.com/24268470/176648734-e36bc6dc-df7c-42be-a89a-c113a71596d6.jpg)

**Comment by J4nsen** [comment]
Totally justified :) Love this project. It just works for me. Kudos!

**Comment by SeByDocKy** [comment]
Yeahh!!!!

**Comment by syssi** [comment]
Thanks for the flowers! I close this issue for better overview / to keep the open issues as low as possible. :-)
