### ISSUE TITLE
JBD BMS (Overkill Solar) Support

### ISSUE THREAD

**Issue by RoySalisbury** [syssi/esphome-jk-bms#153]
Any chance of adding support for the JDB BMS protocol (BLE and/or UART).

**Comment by syssi** [comment]
JDB oder JBD? I assume you are looking for this project: https://github.com/syssi/esphome-jbd-bms

**Comment by RoySalisbury** [comment]
JDB/JBD. I always get that backwards ... But yes... that it.  Was not aware you had that already.  Thanks.

**Comment by RoySalisbury** [comment]
Hopefully BLE support will be added as well..
