### ISSUE TITLE
REQ: JST Connector size

### ISSUE THREAD

**Issue by drbytes** [syssi/esphome-jk-bms#156]
I'd like to connect to the BMS using RS485, does anyone know the correct JST to connect to the GPS port (blue box below) ? I tried JST2.0 4 PIN but that's too large.

![image](https://user-images.githubusercontent.com/507820/186254141-0bf55d18-b8ff-444d-a2d6-ac82e5bded32.png)

**Comment by syssi** [comment]
The connector is called 4 Pin, JST 1.25mm pitch.

**Comment by drbytes** [comment]
Thanks!
