### ISSUE TITLE
Multiple RS485 masters possible?

### ISSUE THREAD

**Issue by Salve87** [syssi/esphome-jk-bms#187]
Hey guys 
I‘m totally new to the rs485 world.

Currently I’m using the rs485 adapter to communicate to the Venus os via usb 

i would love to add a esp to view the data via wifi. 
how can I add the esp, to the existing configuration?
Pictures would be great 

regards

**Comment by syssi** [comment]
You cannot have two RS485 masters on a single bus. I assume you will confuse the VenusOS implementation if you add a second master to the RS485 bus. You could try to add the ESP as passive component (RX-only) to the bus. In best case the ESPHome implementation is able to recycle/decode the responses on the bus requested by VenusOS.
