### ISSUE TITLE
Which port to use? B2A8S20P provides RS485 and GPS/UART-TTL

### ISSUE THREAD

**Issue by claib** [syssi/esphome-jk-bms#188]
hi there
got a brand new B2A8S20P which has 2 Ports : RS485 (3 Pin ) and GPS ( 4 Pin )
which to use ? and which pins ?
Both connectors do have ca 1mm pitch

best regards
Christoph

**Comment by syssi** [comment]
Could you provide a photo of the connectors? I'm confused. ;-)

**Comment by claib** [comment]
![grafik](https://user-images.githubusercontent.com/8424229/194898064-eac72d95-163e-436d-bdad-1a2bc964239c.png)

**Comment by claib** [comment]
the RS485 Port is a 3 pin, and i'm wondering which is A, B and ground ;-)

**Comment by syssi** [comment]
Good question? I will ask Hankzor about some details of the new connector.

**Comment by claib** [comment]
i can confirm that it is the 4 port connector labeled " GPS ". The pins ( view from upside ) are: GND, TX, RX, V+
it is a TTL level interface, preferably connected isolated.

**Comment by syssi** [comment]
The GPS (= UART-TTL) port is well tested and supported by this component. If you are looking for a short term solution you should use this port.

**Comment by syssi** [comment]
I talked to Hankzor BMS but didn't got infos about RS485 labeled port.

Let's close this issue for now.
