### ISSUE TITLE
Error reading max current from JK BMS

### ISSUE THREAD

**Issue by SerialVelocity** [syssi/esphome-jk-bms#190]
Looks like there is a rounding error:
```
Invalid value for number.jk_bms_max_charge_current: 200.000015 (range 1.0 - 200.0)
```

I'm assuming it is due to this:
https://github.com/syssi/esphome-jk-bms/blob/fc6007433d3d69fdbc700c23af41a70ff8ed45db/components/jk_bms_ble/number/__init__.py#L218

It looks like the rounding should happen before checking the max value.

**Comment by syssi** [comment]
Thanks for your report! I will have a look.
