### ISSUE TITLE
Wrong readings via BLE

### ISSUE THREAD

**Issue by proasnet** [syssi/esphome-jk-bms#203]
Hi, today I found in a history, and in real time for some seconds very interesting data from BMS. I thing, that is bad calculated in esp, not in bms. Please see attached picture. I see it on my both BMS, but on both with issue
https://github.com/syssi/esphome-jk-bms/issues/189
My battery is 280Ah, and my max load currend is 25A, max charging current in this time 30A
![over](https://user-images.githubusercontent.com/76579362/199924513-416109ce-088c-4769-af1d-4c69e2cef451.jpg)
![history](https://user-images.githubusercontent.com/76579362/199924880-262639b4-ab2d-4810-8187-ad2ddeeb782a.jpg)

**Comment by syssi** [comment]
Could you enable the debug output of the `uart` component and provide some logs? What has happend at 20 o'clock?

**Comment by proasnet** [comment]
Well, I checked the values ​​via mobile phone directly from the bms and everything is normal there. I had to unplug the esp from power to connect. After reconnecting the esp, everything works normally from one bms to ha as both, the other one does not give data.
I don't remember any extraordinary event yesterday at 8 pm.

**Comment by syssi** [comment]
Let's close the issue for now. Feel free to re-open the issue if you hit the problem again.
