### ISSUE TITLE
Where to buy the connection cable 

### ISSUE THREAD

**Issue by prezes210** [syssi/esphome-jk-bms#206]
Hello team!

Newbie question: where I can buy cable to connect jkbms RS port with ESP?
I mean the cable visible in the readme, with 4 pins.

![circuit](https://user-images.githubusercontent.com/116286414/200127316-3d5b8fdb-211f-404e-bc7a-ae4b79db4186.jpeg)

**Comment by syssi** [comment]
The connector is called 4 Pin, **JST 1.25mm pitch**: https://de.aliexpress.com/item/1005002332868366.html

**Comment by prezes210** [comment]
Thank you so much @syssi !
