### ISSUE TITLE
JK-BD4A17S4P ESP32 Keeps restarting

### ISSUE THREAD

**Issue by Condor-XYZ** [syssi/esphome-jk-bms#221]
Hello Unfortunately, my ESP32 keeps restarting. Apparently the software is not entirely compatible with my JK-BD4A17S4P BMS.
can i do something there?

[logs_jk-bms_logs.txt](https://github.com/syssi/esphome-jk-bms/files/10104100/logs_jk-bms_logs.txt)

**Comment by syssi** [comment]
Could you provide some details (hardware & software version) about your BMS model? Do you miss some important measurements?

**Comment by Condor-XYZ** [comment]
measured values are all there that i need
![1669642962271](https://user-images.githubusercontent.com/75220856/204292883-113a4abc-06f2-45e0-9982-2bbda3095c29.jpg)

**Comment by syssi** [comment]
These log messages are fine:

```
[18:38:16][D][jk_bms_ble:626]: Unknown168: 9E.06.00.00.00.00.00.00.00.00.00.00.00.00.07.00.01.00.00.00.0B.04.00.00.00.00.B1.28.41.40.00.00.00.00.E2.04.36.E7.00.00.00.01.00.05.00.00 (46)
[18:38:16][D][jk_bms_ble:640]: Unknown189: 04 00
[18:38:16][D][jk_bms_ble:644]: Unknown192: 00
[18:38:16][D][jk_bms_ble:646]: Unknown193: 00 B1 (0x00 0x8D)
[18:38:16][D][jk_bms_ble:648]: Unknown195: 28 41 (0x21 0x40)
```

There are some bytes at the response payload of which the purpose is not known. You could decrease the log level of the `jk_bms_ble` component from `DEBUG` to `INFO` to get rid of the noise.

Did you build the project with the recommended `ESP-IDF` framework or Arduino?

**Comment by Condor-XYZ** [comment]
I used the ESP-IDF framework.
If I let it run like this for longer, the BMS has probably crashed. definitely no longer accessible with BLE (oh not on the smartphone)

**Comment by syssi** [comment]
Could you check the red status LED? The BMS is able to handle a single BLE connection. If your ESP32 is connected to the BMS you cannot establish a connection with the Android app anymore and vice-versa. An active connection is indicated by a solid red LED. If the LED blinks the BMS is able to pick up a new connection. If the LED is off the BMS did an emergency shutdown.

**Comment by syssi** [comment]
Keep me updated. :-) I keep my fingers crossed that it's no general issue of your hardware version. A assume a new / another BLE module is used now.

**Comment by Condor-XYZ** [comment]
Was aber noch zu klären wäre wieso der ESP immer wieder einen neustart macht

**Comment by syssi** [comment]
Could you update to the most recent ESPHome version and rebuild + flash the device? The BLE client implementation is changed.

**Comment by Condor-XYZ** [comment]
the same
[Log.txt](https://github.com/syssi/esphome-jk-bms/files/10105748/Log.txt)

**Comment by Condor-XYZ** [comment]
Yes, without MQTT it works.
my MQTT server is from Iobroker and runs with the rest of the smart home devices without any problems... is there anything to watch out for with ESPHome?

**Comment by syssi** [comment]
This is another user having the same issue which could be solved by using mosquitto as MQTT broker: https://github.com/syssi/esphome-jk-bms/issues/211

Could you try to use another broker? Another idea is to capture the traffic between the ESPHome node and your MQTT broker to get an idea what's the different (too many messages? different handshake? protocol version?).

**Comment by Condor-XYZ** [comment]
I changed the settings of the MQTT client in Iobroker and that's it. Thanks for your help

before:
![MQTT-Before](https://user-images.githubusercontent.com/75220856/204857389-a17733e9-ec7a-4ed1-95c3-dc5b81b105d3.JPG)
after:
![MQTT-after](https://user-images.githubusercontent.com/75220856/204857410-349d1bef-db18-46d3-bfe4-309e838a33d1.JPG)

**Comment by syssi** [comment]
Good job! Feel free to close the issue if it's solved!

**Comment by syssi** [comment]
@Condor-XYZ Could you flash the most recent release of this component? I would like to make sure you should use `protocol_version: JK02_32S` in future or not.

**Comment by syssi** [comment]
Thanks for your feedback! Good to know the frame structure of your BMS at software version 11 wasn't changed.
