### ISSUE TITLE
Build error of the example

### ISSUE THREAD

**Issue by AlexThePotter** [syssi/esphome-jk-bms#225]
See log below.

Tried to instal the example on espdev board (esp32).
Install through hass esphome. Doesn't build from cmake  - any ideas?

```
INFO Reading configuration /config/esphome/bms.yaml...
INFO Updating https://github.com/syssi/esphome-jk-bms.git@main
INFO Generating C++ source...
INFO Compiling app...
Processing jk-bms (board: esp32dev; framework: espidf; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40402.0 (4.4.2) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Reading CMake configuration...
-- Building ESP-IDF components for target esp32
-- Configuring incomplete, errors occurred!
See also "/data/jk-bms/.pioenvs/jk-bms/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:201 (message):
  Failed to resolve component 'cxx'.
Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:227 (__build_resolve_and_add_req)
  /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:509 (__build_expand_requirements)
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:384 (idf_build_process)
  CMakeLists.txt:3 (project)

```

**Comment by syssi** [comment]
Please make sure your home directory and build folder is on the same filesystem / mountpoint. Cross filesystem builds aren't supported out of the box.

**Comment by AlexThePotter** [comment]
That's all hidden behind the Esphome addon from HASS? Not sure I can control that? or even check?

**Comment by syssi** [comment]
Which ESPHome version / addon version do you use? I would like to make sure your setup is up-to-date before creating an issue upstream.

**Comment by AlexThePotter** [comment]
The latest 2022.12.3

**Comment by syssi** [comment]
Could you tell me the CPU architecture of your HASS OS setup?

**Comment by AlexThePotter** [comment]
Pi 4

**Comment by syssi** [comment]
In this case the issue is related to https://github.com/esphome/issues/issues/3076 and pretty hard to solve. You should pick a x86 host instead and install ESPHome manually here (`pip3 install esphome`). The command line tool (`esphome`) can be used to build, compile and flash the YAML configuration by:

```
esphome run example.yaml
```

**Comment by AlexThePotter** [comment]
Thanks,

Will give that a go.

**Comment by AlexThePotter** [comment]
Nope this doesn't fix this issue.

Ran on windows 10. Fresh latest python, latest esphome. On intel x86.

`fatal: not a git repository (or any of the parent directories): .git
CMake Error at C:/Users/Alex/.platformio/packages/framework-espidf/tools/cmake/build.cmake:454 (message):
  C:\Users\Alex\AppData\Local\Programs\Python\Python311\python.exe: Error
  while finding module specification for
  'idf_component_manager.prepare_components' (ModuleNotFoundError: No module
  named 'idf_component_manager')

Call Stack (most recent call first):
  C:/Users/Alex/.platformio/packages/framework-espidf/tools/cmake/project.cmake:384 (idf_build_process)
  CMakeLists.txt:3 (project)
`

**Comment by syssi** [comment]
Sorry for the inconvenience. Usually ESPHome builds fine on any CPU arch expect for `arm64` (your Raspi 4). My windows knowledge is very limited and I cannot provide much support here. Do you have access to a Ubuntu host? The project setup will look very similar to this screencast:

![Screencast](https://raw.githubusercontent.com/syssi/esphome-seplos-bms/main/install.gif)
