### ISSUE TITLE
JK_B2A8S20P (SW V11.14H)   current sensor not working

### ISSUE THREAD

**Issue by starfish1107** [syssi/esphome-jk-bms#243]
the current sensor shows 0  despite app shows some current.

**Comment by syssi** [comment]
Could yout provide some more details? Do use use UARR-TTL or BLE? Could you increase the log level (see the "Debug" section of the logs) and provide some logs? I'm interested in some raw frames of your BMS which is decoded to 0 amps but should decoded to something else.

**Comment by starfish1107** [comment]
found the reason. It has nothing to do with esphome-jk-bms fortunately. my jk-bms unit shows 0  below 0,7A and above it shows something but not the correct value. This number is shown in the app and in esphome-jk-bms as well - so everything ok on esphome side. this issue could be deleted or closed.
