### ISSUE TITLE
Read data with ESP8266

### ISSUE THREAD

**Issue by mihaigsm2003** [syssi/esphome-jk-bms#25]
Hi, 
I need to read data voltage for each cell and send to mqtt via ESP
I see code for esphome but for esp8266 i not find eny ino file.

**Comment by syssi** [comment]
Please read the documentation of ESPHome. The is the framework required to generate, compile and upload the firmware from a Yaml file. It's pretty easy and powerful!

**Comment by mihaigsm2003** [comment]
Thanks, i solve with software version from Scotty89, now i have data to grafana.

![image](https://user-images.githubusercontent.com/51678688/147782153-d1211394-a2e7-4418-94cd-9705faa92802.png)

**Comment by syssi** [comment]
If you want to try this project nevertheless please follow the installation guide: https://github.com/syssi/esphome-jk-bms#installation

The framework/command line tool will be used the generate, compile and flash the firmware. No .ino files required. The Yaml configuration describes the full setup / is used to generate the code.
