### ISSUE TITLE
JKBMS Mac Address 

### ISSUE THREAD

**Issue by Septain21** [syssi/esphome-jk-bms#268]
Hello

I can't find the mac address of the JKBMS, could someone tell me where I can find this information to insert into the code

THANKS

**Comment by syssi** [comment]
You could flash this YAML as first step: https://github.com/syssi/esphome-jk-bms/blob/main/esp32-ble-scanner.yaml

It will print all seen BLE devices including the MAC address to the log.

**Comment by Septain21** [comment]
I used an android application to scan the bluetooth it did not work with your program.

THANKS
