### ISSUE TITLE
When uart cable is disconnected previous values are kept and not set to null

### ISSUE THREAD

**Issue by jrventer** [syssi/esphome-jk-bms#273]
When the uart cable to the BMS is disconnected for whatever reason the previous values are kept. This can lead to issue not discovered for a long time until it is too late.

 I suggest either setting the values to null when there is no response from the BMS or have a last updated variable that you can track to see when last the value was updated. Both options might also be option.

**Comment by syssi** [comment]
Good point! I will implement the first suggestion. The second is already available if you use Home Assistant or another Home Automation which keeps track of the latest update per sensor.

**Comment by syssi** [comment]
There is a new binary sensor called `online_status` now:

```
binary_sensor:
  - platform: jk_bms
    online_status:
      name: "${name} online status"
```

If the BMS doesn't respond (on 5 consecutive updates/requests) all sensor values are changed to `Unknown` (NaN), the `online_status` resports `Disconnected` (false) and the text sensor `errors` will show `Offline`.

**Comment by jrventer** [comment]
Great thanks I will recompile and test this.

**Comment by syssi** [comment]
I'm implementing a pretty similar setup here: https://github.com/syssi/esphome-virtual-can-bms

Could you share some details about your inverter (model) and the canbus id / registers you are pushing to the inverter via canbus?

**Comment by jrventer** [comment]
> I'm implementing a pretty similar setup here: https://github.com/syssi/esphome-virtual-can-bms
> 
> Could you share some details about your inverter (model) and the canbus id / registers you are pushing to the inverter via canbus?

Hi sorry missed this message. The 1st integration I am testing is with a Voltronix Axpert King II using the Soltaro CAN Protocol. I will soon start also to test with a Sunsynk/Deye Inverter using the Pylontech CAN protocol.

Below is the can bus specific config I am busy using - reworked some of the config from [https://github.com/Uksa007/esphome-jk-bms-can](url) to work with Soltaro protocol supported by the Axpert inverter.

`spi:
  id: McpSpi
  clk_pin: ${spican_clk_pin}
  mosi_pin: ${spican_mosi_pin}
  miso_pin: ${spican_miso_pin}

canbus:
  - platform: mcp2515
    spi_id: McpSpi
    cs_pin: ${spican_cs_pin}
    #mode: LOOPBACK
    #clock: 8MHZ
    can_id: 4
    bit_rate: 500kbps
    on_frame:
    - can_id: 0x305
      then:
      - lambda: |-
          std::string b(x.begin(), x.end());
          ESP_LOGI("main", "received can id: 0x305 ascii: %s", &b[0] );
          id(can_305_rx) = 0;
interval:
  - interval: 1000ms
    then:
      - if:
          condition:
            - binary_sensor.is_on: online_status
          then:
          - canbus.send: # BMS instructs inverter: Charge Volts, Charge Amps, Discharge Amps, Min voltage
              use_extended_id: True
              can_id: 0x1872
              data: !lambda |-
                uint8_t can_mesg[7];
                if (((!id(charging).state) | (!id(inverter_charging).state)) & (id(charge_status) != "Disabled")) {
                  id(charge_status) = "Disabled";
                  id(can_disable_charge_script).execute();
                } else if (id(inverter_chg_on).state) {
                    id(charge_status) = "Bulk Manually";
                } else if ((id(charging).state) & (id(inverter_charging).state) & (id(charge_status) == "Disabled")) {
                  id(charge_status) = "Wait";
                  id(can_enable_charge_script).execute();
                } else if ((!id(inverter_chg_on).state) & (id(charge_status) == "Bulk Manually")) {
                  id(charge_status) = "Wait";
                } else if (id(total_voltage).state <= (id(charging_voltage).state - ${rebulk_offset})) { ///Bulk Charge eg 53.6v 10% 
                    if (id(absorption_script).is_running()) id(absorption_script).stop();
                    id(charge_status) = "Bulk";
                } else if ((id(total_voltage).state > (id(charging_voltage).state - ${rebulk_offset})) & (id(total_voltage).state < (id(charging_voltage).state - 0.05))) { ///If in startup rebulk
                        if (id(charge_status) == "Startup") {
                            id(charge_status) = "Bulk"; /// If in startup, 10% low rebulk
                        }
                } else if (id(total_voltage).state >= (id(charging_voltage).state  - 0.05)) { ///10 % from top start absorption timer
                        if (id(charge_status) == "Bulk") {
                            id(charge_status) = "Absorption";
                            if (!id(absorption_script).is_running()) id(absorption_script).execute();
                        }
                } else {
                    id(charge_status) = "Wait";
                }
                if ((id(charge_status) == "Bulk") | (id(charge_status) == "Absorption") | (id(inverter_chg_on).state)) {
                  can_mesg[0] = uint16_t(id(charging_voltage).state * 10) & 0xff;
                  can_mesg[1] = uint16_t(id(charging_voltage).state * 10) >> 8 & 0xff;
                  can_mesg[4] = uint16_t(id(charging_current).state * 10) & 0xff;
                  can_mesg[5] = uint16_t(id(charging_current).state * 10) >> 8 & 0xff;
                } else {
                  can_mesg[0] = 0;
                  can_mesg[1] = 0;
                  can_mesg[4] = 0;
                  can_mesg[5] = 0;
                }
                if ((!id(charging).state) | (!id(inverter_charging).state)) { /// Overides to disable charging
                  can_mesg[0] = 0;
                  can_mesg[1] = 0;
                  can_mesg[4] = 0;
                  can_mesg[5] = 0;
                }
                if ((id(discharging).state) & (id(inverter_discharging).state)) {
                  can_mesg[6] = uint16_t(${discharge_a} * 10) & 0xff;
                  can_mesg[7] = uint16_t(${discharge_a} * 10) >> 8 & 0xff;
                } else {
                  can_mesg[6] = 0x00;
                  can_mesg[7] = 0x00;
                }
                can_mesg[2] = uint16_t(${min_dischange_v} * 10) & 0xff;
                can_mesg[3] = uint16_t(${min_dischange_v} * 10) >> 8 & 0xff;
                id(charging_status).publish_state(id(charge_status));
                ESP_LOGD("main", "send can id: 0x1872 hex: %x %x %x %x %x %x %x %x", can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]);
                ESP_LOGI("main", "send can id: Charge Status %s", id(charge_status).c_str());
                return {can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]};
          - delay: 10ms

      - if:
          condition:
            - binary_sensor.is_on: online_status
          then:
            - canbus.send: # Actual Volts, Capacity
                use_extended_id: True
                can_id: 0x1874
                data: !lambda |-
                  uint8_t can_mesg[7];
                  can_mesg[0] = uint16_t(id(total_voltage).state * 10) & 0xff; 
                  can_mesg[1] = uint16_t(id(total_voltage).state * 10) >> 8 & 0xff;
                  can_mesg[2] = int16_t(${absorption_v} * 10) & 0xff;
                  can_mesg[3] = int16_t(${absorption_v} * 10) >> 8 & 0xff; 
                  can_mesg[4] = int16_t(id(capacity_remaining).state) & 0xff;
                  can_mesg[5] = 0x00;
                  can_mesg[6] = 0x00;
                  can_mesg[7] = 0x01;
                  ESP_LOGD("main", "end can id: 0x1874 hex: %x %x %x %x %x %x %x %x", can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]);
                  return {can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]};
            - delay: 10ms

script:
  - id: absorption_script
    then:
      - lambda: id(charge_status) = "Absorption";
      - delay: ${absorption_time}min
      - lambda: id(charge_status) = "Wait";

  - id: can_disable_charge_script
    then:
      - canbus.send: # Disable Charging
          use_extended_id: True
          can_id: 0x1876
          data: !lambda |-
            uint8_t can_mesg[7];
            can_mesg[0] = 0x01;
            can_mesg[1] = 0x00;
            can_mesg[2] = 0x00;
            can_mesg[3] = 0x00; 
            can_mesg[4] = 0x00;
            can_mesg[5] = 0x00;
            can_mesg[6] = 0x00;
            can_mesg[7] = 0x00;
            ESP_LOGI("main", "end can id: 0x1876 hex: %x %x %x %x %x %x %x %x", can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]);
            return {can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]};
      - delay: 10ms
      - canbus.send: # Heartbeat 1
          use_extended_id: True
          can_id: 0x187b
          data: !lambda |-
            uint8_t can_mesg[7];
            can_mesg[0] = 0x00;
            can_mesg[1] = 0x00;
            can_mesg[2] = 0x00;
            can_mesg[3] = 0x00; 
            can_mesg[4] = 0x00;
            can_mesg[5] = 0x00;
            can_mesg[6] = 0x00;
            can_mesg[7] = 0x00;
            ESP_LOGI("main", "end can id: 0x187b hex: %x %x %x %x %x %x %x %x", can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]);
            return {can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]};
      - delay: 10ms

  - id: can_enable_charge_script
    then:
      - canbus.send: # Enable Charging
          use_extended_id: True
          can_id: 0x1876
          data: !lambda |-
            uint8_t can_mesg[7];
            can_mesg[0] = 0x00;
            can_mesg[1] = 0x00;
            can_mesg[2] = 0x00;
            can_mesg[3] = 0x00; 
            can_mesg[4] = 0x00;
            can_mesg[5] = 0x00;
            can_mesg[6] = 0x00;
            can_mesg[7] = 0x00;
            ESP_LOGI("main", "end can id: 0x1876 hex: %x %x %x %x %x %x %x %x", can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]);
            return {can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]};
      - delay: 10ms
      - canbus.send: # Heartbeat 1
          use_extended_id: True
          can_id: 0x187b
          data: !lambda |-
            uint8_t can_mesg[7];
            can_mesg[0] = 0x00;
            can_mesg[1] = 0x00;
            can_mesg[2] = 0x00;
            can_mesg[3] = 0x00; 
            can_mesg[4] = 0x00;
            can_mesg[5] = 0x00;
            can_mesg[6] = 0x00;
            can_mesg[7] = 0x00;
            ESP_LOGI("main", "end can id: 0x187b hex: %x %x %x %x %x %x %x %x", can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]);
            return {can_mesg[0], can_mesg[1], can_mesg[2], can_mesg[3], can_mesg[4], can_mesg[5], can_mesg[6], can_mesg[7]};
      - delay: 10ms`
