### ISSUE TITLE
MQTT Issue

### ISSUE THREAD

**Issue by andyw73** [syssi/esphome-jk-bms#305]
When only using mqtt protocol and not home assistant api a 'homeassistant' topic also gets sent to the mqtt broker (this doesn't keep updating the sensors and from what i can tell only happens on reboots). How can we stop this behaviour from happening as I dont want to integrate this into Ha. Thanks in advance.

![esphome-jk-bms](https://user-images.githubusercontent.com/90845783/230598236-3200e53d-0d5e-4a7c-ad02-8abbd633d220.png)

**Comment by syssi** [comment]
The `homeassistant` topic is used for meta informations about the node / exposed sensors to allow Home Assistant to auto-discover the node. Please lookup the parameters of the `mqtt` component of ESPHome. There is an option called `discovery` which can be disabled. This will suppress the auto-discovery messages.

**Comment by syssi** [comment]
```
mqtt:
   broker: !secret mqtt_host
   id: mqtt_client
   discovery: false
```

**Comment by andyw73** [comment]
Thank you that resolved the issue.
