### ISSUE TITLE
JK  BMS B2A20S20P Heat CAN/RS485 problem with connection

### ISSUE THREAD

**Issue by Tesla72PL** [syssi/esphome-jk-bms#309]
Hello, I uploaded the following code for ESP8266 D1 mini and unfortunately nothing works - what am I doing wrong?

```
substitutions:
  name: jk-bms
  device_description: "Monitor a JK-BMS via UART-TTL"
  external_components_source: github://syssi/esphome-jk-bms@main
  tx_pin: GPIO1
  rx_pin: GPIO3

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.4.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

api:
  encryption:
    key: "..."

ota:
  password: "..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jk-Battery-01-Info"
    password: "..."

logger:
  baud_rate: 0
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt

uart:
  - id: uart0
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    debug:
     direction: BOTH

jk_modbus:
  - id: modbus0
    uart_id: uart0
    rx_timeout: 50ms

jk_bms:
  - id: bms0
    jk_modbus_id: modbus0
    update_interval: 5s

binary_sensor:
  - platform: jk_bms
    balancing:
      name: "${name} balancing"
    balancing_switch:
      name: "${name} balancing switch"
    charging:
      name: "${name} charging"
    charging_switch:
      name: "${name} charging switch"
    discharging:
      name: "${name} discharging"
    discharging_switch:
      name: "${name} discharging switch"
    dedicated_charger_switch:
      name: "${name} dedicated charger switch"
    online_status:
      name: "${name} online status"

sensor:
  - platform: jk_bms
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"
    cell_voltage_17:
      name: "${name} cell voltage 17"
    cell_voltage_18:
      name: "${name} cell voltage 18"
    cell_voltage_19:
      name: "${name} cell voltage 19"
    cell_voltage_20:
      name: "${name} cell voltage 20"
    cell_voltage_21:
      name: "${name} cell voltage 21"
    cell_voltage_22:
      name: "${name} cell voltage 22"
    cell_voltage_23:
      name: "${name} cell voltage 23"
    cell_voltage_24:
      name: "${name} cell voltage 24"
    power_tube_temperature:
      name: "${name} power tube temperature"
    temperature_sensor_1:
      name: "${name} temperature sensor 1"
    temperature_sensor_2:
      name: "${name} temperature sensor 2"
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    capacity_remaining:
      name: "${name} capacity remaining"
    capacity_remaining_derived:
      name: "${name} capacity remaining derived"
    temperature_sensors:
      name: "${name} temperature sensors"
    charging_cycles:
      name: "${name} charging cycles"
    total_charging_cycle_capacity:
      name: "${name} total charging cycle capacity"
    battery_strings:
      name: "${name} battery strings"
    errors_bitmask:
      name: "${name} errors bitmask"
    operation_mode_bitmask:
      name: "${name} operation mode bitmask"
    total_voltage_overvoltage_protection:
      name: "${name} total voltage overvoltage protection"
    total_voltage_undervoltage_protection:
      name: "${name} total voltage undervoltage protection"
    cell_voltage_overvoltage_protection:
      name: "${name} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name} cell voltage overvoltage recovery"
    cell_voltage_overvoltage_delay:
      name: "${name} cell voltage overvoltage delay"
    cell_voltage_undervoltage_protection:
      name: "${name} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name} cell voltage undervoltage recovery"
    cell_voltage_undervoltage_delay:
      name: "${name} cell voltage undervoltage delay"
    cell_pressure_difference_protection:
      name: "${name} cell pressure difference protection"
    discharging_overcurrent_protection:
      name: "${name} discharging overcurrent protection"
    discharging_overcurrent_delay:
      name: "${name} discharging overcurrent delay"
    charging_overcurrent_protection:
      name: "${name} charging overcurrent protection"
    charging_overcurrent_delay:
      name: "${name} charging overcurrent delay"
    balance_starting_voltage:
      name: "${name} balance starting voltage"
    balance_opening_pressure_difference:
      name: "${name} balance opening pressure difference"
    power_tube_temperature_protection:
      name: "${name} power tube temperature protection"
    power_tube_temperature_recovery:
      name: "${name} power tube temperature recovery"
    temperature_sensor_temperature_protection:
      name: "${name} temperature sensor temperature protection"
    temperature_sensor_temperature_recovery:
      name: "${name} temperature sensor temperature recovery"
    temperature_sensor_temperature_difference_protection:
      name: "${name} temperature sensor temperature difference protection"
    charging_high_temperature_protection:
      name: "${name} charging high temperature protection"
    discharging_high_temperature_protection:
      name: "${name} discharging high temperature protection"
    charging_low_temperature_protection:
      name: "${name} charging low temperature protection"
    charging_low_temperature_recovery:
      name: "${name} charging low temperature recovery"
    discharging_low_temperature_protection:
      name: "${name} discharging low temperature protection"
    discharging_low_temperature_recovery:
      name: "${name} discharging low temperature recovery"
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    current_calibration:
      name: "${name} current calibration"
    device_address:
      name: "${name} device address"
    sleep_wait_time:
      name: "${name} sleep wait time"
    alarm_low_volume:
      name: "${name} alarm low volume"
    manufacturing_date:
      name: "${name} manufacturing date"
    total_runtime:
      name: "${name} total runtime"
#    start_current_calibration:
#      name: "${name} start current calibration"
    actual_battery_capacity:
      name: "${name} actual battery capacity"
#    protocol_version:
#      name: "${name} protocol version"

text_sensor:
  - platform: jk_bms
    errors:
      name: "${name} errors"
    operation_mode:
      name: "${name} operation mode"
    battery_type:
      name: "${name} battery type"
    password:
      name: "${name} password"
    device_type:
      name: "${name} device type"
    software_version:
      name: "${name} software version"
    manufacturer:
      name: "${name} manufacturer"
    total_runtime_formatted:
      name: "${name} total runtime formatted"
```

**Comment by syssi** [comment]
Please check the controls tab of the Android app.Do you see here a switch to choose between CAN and RS485?

**Comment by syssi** [comment]
Where did you buy the BMS?

**Comment by syssi** [comment]
Good question. In general your setup should work:

1. Your wiring sounds correct
2. You are using the hardware UART of an ESP8266 + the `logger` doesn't write to GPIO1/3 because of `baud_rate: 0`
3. You did enable the RS485 switch. This switch is new and wasn't available in the past.

Could you enable the `debug` mode of the `uart` component and provide some logs:

```
logger:
  baud_rate: 0
  level: DEBUG

uart:
  id: uart0
  baud_rate: 115200
  rx_buffer_size: 384
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  debug:
    direction: BOTH
```

I would like to know there is no response at all or noise.

**Comment by syssi** [comment]
> When I connect to the bms, once there something happens and it stops working and no longer connects via wi-fi....

That's not good! How do you power the ESP?

**Comment by syssi** [comment]
Do you mean a USB power plug? I would like to make sure you don't power the ESP using the battery + buck converter.

**Comment by syssi** [comment]
Your wiring looks good but the labels of your BMS are confusing. My left port is labeled as "CAN". The right port is labeled as GPS/RS485. May be the hardware layout has changed?!

**Comment by syssi** [comment]
I know the protocol description. It's the implemented protocol for the UART-TTL connection.

**Comment by syssi** [comment]
Could you do some measurements? I would like a complete documentation of your issue here.

1. Please measure the voltage between
    GND <-> RX
    GND <-> TX
    GND <-> VBAT
2. Please measure the resistance between
    GND <-> RX
    GND <-> TX

**Comment by syssi** [comment]
On.

**Comment by maxsarges** [comment]
Hi,

i have a JK-BD6A20S10P. This works fine with the Bluetooth module. 

I know wanted to connect it through RS485 also. I got stuck at the same Point. Connecting it to the "GPS" Port with the jst Connector but no Communication.

Mine looks the same as the above picture shows, but i don't have the settings in the APP (CAN/RS485).

When i connect everything my ESP still produces LOG files, so i guess it doesn't hang up like yours. 

I will try some more things, including Voltage and resistance Measurements, but any idea is welcomed!

Waiting for your test's with your newly orderd BMS.

kind Regards 
Max

**Comment by syssi** [comment]
@maxsarges Please provide the software and hardware version of your BMS too. I guess the CAN/RS485 switch is available since firmware version 11.

**Comment by maxsarges** [comment]
Hi,

I have Version 10, maybe thats the reason why i don't have the Button.

![Screenshot_20230429-214649.png](https://user-images.githubusercontent.com/130499653/235323173-bfd3ea3d-d970-4821-a4d3-a7d7c69ed629.png)

**Comment by syssi** [comment]
Please enable the debug output of the `uart` component:

https://github.com/syssi/esphome-jk-bms#debugging

**Comment by syssi** [comment]
`>>>` indicates outgoing traffic (the cell info requests).
`<<<` indicates incoming traffic.

It looks like your new BMS doesn't respond too. The received `0xFF` looks like garbage. Please double check your data cable and make sure GND is attached properly and the cable length is less than 10 centimeters.

**Comment by syssi** [comment]
Does both devices work now?

**Comment by syssi** [comment]
My question was about your BMS (first and second one).

**Comment by syssi** [comment]
Could you tell me the model name, software and hardware version of the working BMS? I would like to extend the docs.

**Comment by syssi** [comment]
Good job! And happy birthday(?) ;-)

**Comment by syssi** [comment]
Your screenshot contains a birthday cake at the top. I guessed it's your birthday today. ;-)

**Comment by kev300** [comment]
Most buck convertes forward full input voltage to output if they fail, so there is that danger already.
In addition they could output voltage spikes if the output capacitor is small. The serial connections are very sensitiv to voltage spikes. Especially those, which can't handle 5V logic level. (ESP, the JK-BMS are both 3.3V)

So maybe you can avoid this dangers with a big capacitor after the buck converter + zener diodes which limit max voltage in addition. They need to be stronger than the converter, so they don't break if the converter fails. 😁

**Comment by eMindFfM** [comment]
Hi all,
looking at the new Version 11 from the JK-BMS I got this information:

Hello Torsten,I had talked with factory and our purchase manager again.They said for these two version,they are just different software, the function is the same.As for the two functions you mentioned, the software just reserves them, but they cannot be used. If you need to use it, we need to buy another version from the factory.

So it seems to be the case, that there are no new HW components yet, only the SW is updated.

**Comment by lucize** [comment]
I have the version with CAN switch to RS485 and I can confirm that it will activate the modebus protocol (as somehow I managed to damage the gps circuit) also I can read some holding registers using an usb adapter, but not all the values are present or I don't know how to read them (only 0-29 works), I'm waiting for a rs485 to ttl adapter to see if I can use it on esp

**Comment by syssi** [comment]
@lucize Could you provide the pinout of the CAN/RS485 port and a request + response example?

**Comment by lucize** [comment]
sorry, I'm not good with modebus, for the moment I have this:

can/rs485       |    gps
GND - B - A    |    ....

values should be interger, as the temp is negative for my faulty board

![image](https://github.com/syssi/esphome-jk-bms/assets/6313831/3fdfbc57-2ceb-45d8-b4d3-4a1dd93b26c7)

**Comment by maxsarges** [comment]
I've tried it yesterday many times with different settings, boards and UART's.

But so far no success. Maybe the Board is faulty, but i don't think so.

Maybe it has something to do with GND. Both signals refer to GND of the BMS.

I have for sure connected TX / RX and GND to my ESP32. But maybe the ESP boards differ a little bit. So far this is the only guess i have, but until know i have no solution for that.

Does anybody has another idea what i can do?

Kind regards Max

**Comment by syssi** [comment]
@maxsarges Could you create a new issue an describe your setup + provide some photos of the wiring? These details are important:

1. BMS model
2. Software and hardware version of the BMS
3. Where did you buy the BMS?
4. Did you buy the model with or without CAN support?
5. How do you power your ESP?
6. Which GPIOs do you use?

**Comment by vjlb** [comment]
Here you go @syssi , mine not working at all too:

BMS model - JK_B2A24S15P
Software and hardware version of the BMS - Hard: V11.XW Soft: V11.25
Where did you buy the BMS? - Hankzor
Did you buy the model with or without CAN support? - With CAN
How do you power your ESP? - USB-C
Which GPIOs do you use? 1/3

Tried also with MAX232 UART-TTL

My code:
`substitutions:
  name: jk-bms
  device_description: "Monitor a JK-BMS via UART-TTL"
  external_components_source: github://syssi/esphome-jk-bms@main
  tx_pin: GPIO1
  rx_pin: GPIO3

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.5.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

logger:
  baud_rate: 0
  level: DEBUG

api:

uart:
  - id: uart_0
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

jk_modbus:
  - id: modbus0
    uart_id: uart_0
    rx_timeout: 50ms

jk_bms:
  - id: bms0
    jk_modbus_id: modbus0
    update_interval: 5s

binary_sensor:
  - platform: jk_bms
    balancing:
      name: "${name} balancing"
    balancing_switch:
      name: "${name} balancing switch"
    charging:
      name: "${name} charging"
    charging_switch:
      name: "${name} charging switch"
    discharging:
      name: "${name} discharging"
    discharging_switch:
      name: "${name} discharging switch"
    dedicated_charger_switch:
      name: "${name} dedicated charger switch"
    online_status:
      name: "${name} online status"

sensor:
  - platform: jk_bms
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"
    cell_voltage_17:
      name: "${name} cell voltage 17"
    cell_voltage_18:
      name: "${name} cell voltage 18"
    cell_voltage_19:
      name: "${name} cell voltage 19"
    cell_voltage_20:
      name: "${name} cell voltage 20"
    cell_voltage_21:
      name: "${name} cell voltage 21"
    cell_voltage_22:
      name: "${name} cell voltage 22"
    cell_voltage_23:
      name: "${name} cell voltage 23"
    cell_voltage_24:
      name: "${name} cell voltage 24"
    power_tube_temperature:
      name: "${name} power tube temperature"
    temperature_sensor_1:
      name: "${name} temperature sensor 1"
    temperature_sensor_2:
      name: "${name} temperature sensor 2"
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    capacity_remaining:
      name: "${name} capacity remaining"
    capacity_remaining_derived:
      name: "${name} capacity remaining derived"
    temperature_sensors:
      name: "${name} temperature sensors"
    charging_cycles:
      name: "${name} charging cycles"
    total_charging_cycle_capacity:
      name: "${name} total charging cycle capacity"
    battery_strings:
      name: "${name} battery strings"
    errors_bitmask:
      name: "${name} errors bitmask"
    operation_mode_bitmask:
      name: "${name} operation mode bitmask"
    total_voltage_overvoltage_protection:
      name: "${name} total voltage overvoltage protection"
    total_voltage_undervoltage_protection:
      name: "${name} total voltage undervoltage protection"
    cell_voltage_overvoltage_protection:
      name: "${name} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name} cell voltage overvoltage recovery"
    cell_voltage_overvoltage_delay:
      name: "${name} cell voltage overvoltage delay"
    cell_voltage_undervoltage_protection:
      name: "${name} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name} cell voltage undervoltage recovery"
    cell_voltage_undervoltage_delay:
      name: "${name} cell voltage undervoltage delay"
    cell_pressure_difference_protection:
      name: "${name} cell pressure difference protection"
    discharging_overcurrent_protection:
      name: "${name} discharging overcurrent protection"
    discharging_overcurrent_delay:
      name: "${name} discharging overcurrent delay"
    charging_overcurrent_protection:
      name: "${name} charging overcurrent protection"
    charging_overcurrent_delay:
      name: "${name} charging overcurrent delay"
    balance_starting_voltage:
      name: "${name} balance starting voltage"
    balance_opening_pressure_difference:
      name: "${name} balance opening pressure difference"
    power_tube_temperature_protection:
      name: "${name} power tube temperature protection"
    power_tube_temperature_recovery:
      name: "${name} power tube temperature recovery"
    temperature_sensor_temperature_protection:
      name: "${name} temperature sensor temperature protection"
    temperature_sensor_temperature_recovery:
      name: "${name} temperature sensor temperature recovery"
    temperature_sensor_temperature_difference_protection:
      name: "${name} temperature sensor temperature difference protection"
    charging_high_temperature_protection:
      name: "${name} charging high temperature protection"
    discharging_high_temperature_protection:
      name: "${name} discharging high temperature protection"
    charging_low_temperature_protection:
      name: "${name} charging low temperature protection"
    charging_low_temperature_recovery:
      name: "${name} charging low temperature recovery"
    discharging_low_temperature_protection:
      name: "${name} discharging low temperature protection"
    discharging_low_temperature_recovery:
      name: "${name} discharging low temperature recovery"
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    current_calibration:
      name: "${name} current calibration"
    device_address:
      name: "${name} device address"
    sleep_wait_time:
      name: "${name} sleep wait time"
    alarm_low_volume:
      name: "${name} alarm low volume"
    manufacturing_date:
      name: "${name} manufacturing date"
    total_runtime:
      name: "${name} total runtime"
#    start_current_calibration:
#      name: "${name} start current calibration"
    actual_battery_capacity:
      name: "${name} actual battery capacity"
#    protocol_version:
#      name: "${name} protocol version"

text_sensor:
  - platform: jk_bms
    errors:
      name: "${name} errors"
    operation_mode:
      name: "${name} operation mode"
    battery_type:
      name: "${name} battery type"
    password:
      name: "${name} password"
    device_type:
      name: "${name} device type"
    software_version:
      name: "${name} software version"
    manufacturer:
      name: "${name} manufacturer"
    total_runtime_formatted:
      name: "${name} total runtime formatted"
`

![IMG_20230611_191635](https://github.com/syssi/esphome-jk-bms/assets/83526390/c871bf26-b020-4622-b058-999d06c12291)
![1686507543872](https://github.com/syssi/esphome-jk-bms/assets/83526390/b629035d-7906-42e2-bafe-340ff7e38cc1)

**Comment by syssi** [comment]
> Tried also with MAX232 UART-TTL

What does this mean? Did you attach the MAX232 to the RS232 port of your computer? I hope you haven't pushed -12/+12V into the UART-TTL port.

> Port is working good for sure, used it before with other software monitor via usb to serial converter

@vjlb Could you verify the other software monitor via the serial converter is still working? It's super interesting one software works and the other  / this project isn't working.

**Comment by syssi** [comment]
@vjlb Could you change your YAML to this feature branch + flash the ESP and provide another log? I would like to know some more details about the invalid header warnings:

```
substitutions:
  external_components_source: github://syssi/esphome-jk-bms@debug-decoder
```

**Comment by vjlb** [comment]
> > Tried also with MAX232 UART-TTL
> 
> What does this mean? Did you attach the MAX232 to the RS232 port of your computer? I hope you haven't pushed -12/+12V into the UART-TTL port.
> 
Not to PC mate, connected like this:
![Sem título](https://github.com/syssi/esphome-jk-bms/assets/83526390/d6360970-4497-48f9-af30-bdaa948a5ec3)

I use same connection on this software to monitor my inverter over MQTT:
https://github.com/softwarecrash/Solar2MQTT


> > Port is working good for sure, used it before with other software monitor via usb to serial converter
> 
> @vjlb Could you verify the other software monitor via the serial converter is still working? It's super interesting one software works and the other / this project isn't working.

That's the one i used before to monitor BMS over USB to Serial, but i prefer the ESP solution over the Raspberry PI:
https://github.com/dj-nitehawk/Hybrid-Inverter-Monitor

Will test the branch you suggested

**Comment by vjlb** [comment]
> @vjlb Could you change your YAML to this feature branch + flash the ESP and provide another log? I would like to know some more details about the invalid header warnings:
> 
> ```
> substitutions:
>   external_components_source: github://syssi/esphome-jk-bms@debug-decoder
> ```

Is this my bad?
Trying it wirelessly

INFO ESPHome 2023.5.5
INFO Reading configuration /config/esphome/jk-bms.yaml...
INFO Updating https://github.com/syssi/esphome-jk-bms.git@debug-decoder
INFO Generating C++ source...
INFO Compiling app...
Processing jk-bms (board: d1_mini; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
Compiling /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/jk_modbus/jk_modbus.cpp.o
Compiling /data/jk-bms/.pioenvs/jk-bms/src/main.cpp.o
In file included from src/esphome/components/uart/uart.h:6,
                 from src/esphome/components/jk_modbus/jk_modbus.h:4,
                 from src/esphome/components/jk_modbus/jk_modbus.cpp:1:
src/esphome/components/jk_modbus/jk_modbus.cpp: In member function 'virtual void esphome::jk_modbus::JkModbus::loop()':
src/esphome/components/jk_modbus/jk_modbus.cpp:13:14: error: 'format_hex_pretty' was not declared in this scope
   13 |              format_hex_pretty(&this->rx_buffer_.front(), this->rx_buffer_.size()).c_str());
      |              ^~~~~~~~~~~~~~~~~
src/esphome/core/log.h:114:88: note: in definition of macro 'esph_log_w'
  114 |   esp_log_printf_(ESPHOME_LOG_LEVEL_WARN, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                        ^~~~~~~~~~~
src/esphome/components/jk_modbus/jk_modbus.cpp:12:5: note: in expansion of macro 'ESP_LOGW'
   12 |     ESP_LOGW(TAG, "Buffer cleared due to timeout: %s",
      |     ^~~~~~~~
src/esphome/components/jk_modbus/jk_modbus.cpp:25:16: error: 'format_hex_pretty' was not declared in this scope
   25 |                format_hex_pretty(&this->rx_buffer_.front(), this->rx_buffer_.size()).c_str());
      |                ^~~~~~~~~~~~~~~~~
src/esphome/core/log.h:114:88: note: in definition of macro 'esph_log_w'
  114 |   esp_log_printf_(ESPHOME_LOG_LEVEL_WARN, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                        ^~~~~~~~~~~
src/esphome/components/jk_modbus/jk_modbus.cpp:24:7: note: in expansion of macro 'ESP_LOGW'
   24 |       ESP_LOGW(TAG, "Buffer cleared due to reset: %s",
      |       ^~~~~~~~
*** [/data/jk-bms/.pioenvs/jk-bms/src/esphome/components/jk_modbus/jk_modbus.cpp.o] Error 1
========================== [FAILED] Took 2.56 seconds ==========================

**Comment by syssi** [comment]
I've pushed a probably missing include. Please try again!

**Comment by syssi** [comment]
Please don't use a MAX232 with a JK-BMS! The high logic level could destroy the opto-couplers / UART-TTL port of the BMS.

**Comment by vjlb** [comment]
> Please don't use a MAX232 with a JK-BMS! The high logic level could destroy the opto-couplers / UART-TTL port of the BMS.

Noted!
Will test with other software to make sure it works

**Comment by vjlb** [comment]
Just finished install on RPI, it's working with other monitor software over the same port:
![image](https://github.com/syssi/esphome-jk-bms/assets/83526390/dadd3f22-b22c-40fe-ad5c-8e4831c30569)

Here is the log, very fast outputing those errors BTW:
"Buffer cleared timeout"

[logs_jk-bms_logs (1).txt](https://github.com/syssi/esphome-jk-bms/files/11715672/logs_jk-bms_logs.1.txt)

**Comment by vjlb** [comment]
Looks like sometimes i now get some tiny data, but i lowered the cable lenght

 
[logs_jk-bms_logs (2).txt](https://github.com/syssi/esphome-jk-bms/files/11715844/logs_jk-bms_logs.2.txt)

**Comment by Dimu1234** [comment]
This is my code & connect to HA through ESP32 via Bluetooth

![Untitled](https://github.com/syssi/esphome-jk-bms/assets/100999743/7d39f9a2-d650-454c-aa24-ed4aff72d469)

**Comment by jeremGi** [comment]
merci je galère depuis 3 jours et j'étais dans le même cas et en Bluetooth ca fonctionne

**Comment by chaosnature** [comment]
> @JakobTewes I cannot provide a good answer. I'm a software developer with limited skills in electrical circuits. I'm just aware of users who release magic smoke (destroyed the serial port of the BMS, ESP or buck converter).

Can you assist me i have the same issue
how does one upgrade the firmware?
