### ISSUE TITLE
ESPHome 2023.4.0 validation failure

### ISSUE THREAD

**Issue by jouking** [syssi/esphome-jk-bms#315]
With the version of Home Assistant 2023.4 I get the capture error, how do I have to fix it so that everything continues to work as before?

![imagen](https://user-images.githubusercontent.com/61602218/233836839-9bcccac7-84ea-48df-af0a-1fdda48d812a.png)

**Comment by syssi** [comment]
Please update your YAML: Search for `uart0` and replace all occurrences with `uart_0`.

**Comment by jouking** [comment]
perfect, thank you very much
