### ISSUE TITLE
display full path

### ISSUE THREAD

**Issue by magnetus26** [syssi/esphome-jk-bms#320]
Hello Sebastian,
I im learning how to code ESPHOME so much with you.
you jus got a really nice additionto the lastest jk-bms yaml.
the comment command. I really like it and will ad it to all my yaml files.
also you have the full path display to the yaml on the ESPHOME tab.
how can I add the full path to my codes? I've been looking and reading but cant find the answer.

![image](https://user-images.githubusercontent.com/22038983/234873143-4d433c24-eab3-4602-b6b8-871525444e35.png)
thanks Miguel
73 de KP4MI

**Comment by syssi** [comment]
The first line of the tile is the `esphome.name`. The third line the `esphome.description`. The filename isn't part of the YAML configuration.
