### ISSUE TITLE
max min voltage of cells stange value

### ISSUE THREAD

**Issue by riker65** [syssi/esphome-jk-bms#323]
Hi
do you mind checking those measures:
Can not find them in the app.
values do look strange to me.

![image](https://user-images.githubusercontent.com/20332429/235498051-2f2c0bfb-f236-4724-9cd3-8ea114dc8bf3.png)

also mqtt

![image](https://user-images.githubusercontent.com/20332429/235498156-ff324a44-24b6-458d-abf1-b82590daa65e.png)

thanks Thomas

**Comment by syssi** [comment]
The first screenshot shows the minimum cell voltage. The second screenshot the maximum. The values aren't available via the android app. It's just the lowest and highest value from the list of cell voltages.

**Comment by riker65** [comment]
Hi,  but they are changing very quick, and 7 can not be right, mqtt value
also min voltage 2 and max 8 can not be right? 
are those integer?

**Comment by syssi** [comment]
This is the cell number. It indicates the cell with the min/max voltage.

**Comment by riker65** [comment]
ok understand thanks

**Comment by riker65** [comment]
off topic: do you know a way to sort web output? naming does not work

**Comment by syssi** [comment]
> off topic: do you know a way to sort web output? naming does not work

I don't know. You could ask at the ESPHome discord channel. It looks like a custom iterator is used to loop over all entities and sorting isn't implemented yet.
