### ISSUE TITLE
JK BMS BLE Protocol

### ISSUE THREAD

**Issue by EstyGee** [syssi/esphome-jk-bms#331]
Hello, it's not about [esphome-jk-bms], but it's about reading daa drom JK BMS by my app...

Now i have this:
![image](https://github.com/syssi/esphome-jk-bms/assets/92596788/08e5bd9c-a9a6-4591-ba16-0a8279f31030)

I send to BMS 2 command:
0xffe1:
aa5590eb9700df5288679d0a096b9af6709a17fd
aa5590eb9600f45fe2036dfbe038aabc441234b8

After that i start to recieve data each second, but I was able to decrypt some data. The main thing I need to find is the charge current and the discharge current. Help me please...

First pair: Data from Bluetoothe and after 10 seconds screenshot of app:
![image](https://github.com/syssi/esphome-jk-bms/assets/92596788/20f39fe8-a05a-45cd-af55-d6063c8c3d2d)
![image](https://github.com/syssi/esphome-jk-bms/assets/92596788/09301c85-726e-4030-a221-184056d73a76)

Second pair: Data from Bluetoothe and after 10 seconds screenshot of app:
![image](https://github.com/syssi/esphome-jk-bms/assets/92596788/f0e91d35-f129-4b70-9084-a09c1acc0e8c)
![image](https://github.com/syssi/esphome-jk-bms/assets/92596788/e23a63a9-f05f-420a-930a-5b4a85f5b042)

My English not so good, but I hope you will understood me :)

**Comment by EstyGee** [comment]
Oh, I think I found charge current and charge power?
![image](https://github.com/syssi/esphome-jk-bms/assets/92596788/d1d1508d-b9ec-46bc-97e4-85a4eafe0925)

But where is discharge?

**Comment by EstyGee** [comment]
Ok, solved... it can be negative... Thank for everyone (no one) :)

**Comment by syssi** [comment]
You are on the right track! Keep in mind there are different time zones and everybody needs some rest. :-)

**Comment by syssi** [comment]
https://github.com/syssi/esphome-jk-bms/blob/main/components/jk_bms_ble/jk_bms_ble.cpp#L564-L578
