### ISSUE TITLE
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.

### ISSUE THREAD

**Issue by proasnet** [syssi/esphome-jk-bms#332]
Hi, I update ESPhome today to latest version and is problem with update node, in compilation, I get this message
`WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version`
And compilation exit with failure.
Is any correct way for fix this issue?
Thank you

**Comment by syssi** [comment]
Please reduce your configuration to:

```
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
```

https://github.com/syssi/esphome-jk-bms/blob/main/esp32-ble-example.yaml#L17-L21

**Comment by proasnet** [comment]
Thank you. It works fine.
