### ISSUE TITLE
Component not found: heltec_balancer_ble.

### ISSUE THREAD

**Issue by Zahnpasta83** [syssi/esphome-jk-bms#338]
Does anyone know the problem? Always having the same issue.

![image](https://github.com/syssi/esphome-jk-bms/assets/122221616/07712688-8a7e-4d58-a8c1-fad5d598850c)

**Comment by syssi** [comment]
I assume the `external_components` section is missing in your YAML. Please provide the full YAML so I can try to reproduce the issue.

**Comment by Zahnpasta83** [comment]
You were absolutely right, it's working now. Thank you
