### ISSUE TITLE
B2a8s20p ble not all sensor correct 

### ISSUE THREAD

**Issue by hemskgren** [syssi/esphome-jk-bms#344]
Hi 
My b2a8s20p look to match one existing confirm to work. Using JK02_32S.

![IMG-20230615-WA0004](https://github.com/syssi/esphome-jk-bms/assets/10794918/4194286a-81b5-470c-b893-1ee1e718627a)

* Cell volt is correct but all resistance is 0, same as manual in app.
* all 'tempeture' is off/wrong
* all 'Total' look like static and wrong.
* 'min cell voltage' look to show delta. 

More is wrong but above is easy to see.

I have test uart but not get it to work thru the 4 pin gps port.

**Comment by syssi** [comment]
If it's a version 9 device you should use `protocol_version:  JK02`. Please give it another try!

**Comment by hemskgren** [comment]
I will test it during the weekend.

**Comment by hemskgren** [comment]
Yes, it look OK with JK02
