### ISSUE TITLE
ESPHome 2023.7.0: "Component esp32_ble took a long time for an operation" warning

### ISSUE THREAD

**Issue by gepetto666** [syssi/esphome-jk-bms#354]
Got this error after update esp home.
I don't know if is bms fault , esp module or firmware
Before update this error was not present
Anybody have this issue ? 
Thnks

and the log
[16:28:20][W][component:204]: Component esp32_ble took a long time for an operation (0.47 s).
[16:28:20][W][component:205]: Components should block for at most 20-30ms.

**Comment by syssi** [comment]
This is just a warning of the official `esp32_ble` component. I assume it's unrelated to this project & BMS firmware.

**Comment by syssi** [comment]
Please see the release notes: https://esphome.io/changelog/2023.7.0.html#a-new-warning-in-the-logs
