### ISSUE TITLE
Micro cuts with connection

### ISSUE THREAD

**Issue by jouking** [syssi/esphome-jk-bms#357]
Yesterday I updated ESPHome to version 2023.7.0 and since then the 2 ESPs that I have connected to the jkbms fail, both by UART TTL port and by Bluetooth, they disconnect for 4 or 5 seconds and reconnect for a while and come back disconnect again those few seconds. Is there any problem detected with this latest version of esphome?

**Comment by syssi** [comment]
Yes. It looks like the latest release of ESPHome has some stability issues. See #355

**Comment by syssi** [comment]
Duplicate #355
