### ISSUE TITLE
Info compatibility ESP-WROOM-32

### ISSUE THREAD

**Issue by alesssionico** [syssi/esphome-jk-bms#358]
Hello, I closed the report of the other problem due to converter incompatibility. I wanted to ask you if this can go well, therefore to be applied directly to the rs485 output of the BMS jk B2A20S20P (RX/TX/GND) to the ESP module (gpio Port/GND) and then configure Raspberry via ESP32 ?
Thank you
![Screenshot_20230727_103023](https://github.com/syssi/esphome-jk-bms/assets/134967644/3b437111-8d43-4fcd-bf2c-c65c6af560ae)

**Comment by alesssionico** [comment]
Solved everything works.
Thank you.

**Comment by syssi** [comment]
Good job! Sorry for the late response. I've missed your post.
