### ISSUE TITLE
Current shows a negative value while charging.

### ISSUE THREAD

**Issue by jonadis** [syssi/esphome-jk-bms#36]
Greetings,

Now that I've got things up and running I'm seeing negative values reported in ESPHome for 'current'
`[D][sensor:125]: 'jk-bms current': Sending state -1.49000 A with 2 decimals of accuracy`
when "charging" the battery.  The Bluetooth app shows a positive current as I'd expect.
![Screenshot_2022-02-10-13-41-47-127](https://user-images.githubusercontent.com/24478854/153475611-bea7511d-764f-464d-9b1b-79313cebb27b.jpeg)

**Comment by jonadis** [comment]
"If you charge the battery the current should be positive." ...
 ... agreed, but it shows negative.
 
 "If you discharge the battery by some load the current should be positive." ...
 ... I disagree, I think discharge should show negative, at least that's what the bluetooth app shows, but it shows positive.
 
 Since the behavior is exactly the opposite of what I think it should be, I was able to work around the issue by multiplying the value by -1.  The only oddity there is that 0 shows -0 but I can live with that.
 
```
     current:
      name: "${name} current"
      filters:
        - multiply: -1
```

**Comment by syssi** [comment]
The strange this I've inverted the order here already once: https://github.com/syssi/esphome-jk-bms/issues/23

It looks like there a firmware versions around where the sign is inverted. I like your workaround and don't change the code for now.

**Comment by syssi** [comment]
FYI: https://github.com/syssi/esphome-jk-bms/pull/50
