### ISSUE TITLE
CRC check failed! with JK_B2A8S20P and SW V11.262

### ISSUE THREAD

**Issue by Blackforrestpilot** [syssi/esphome-jk-bms#362]
Hi,
i'm allready using an JK_B2A8S20P with an ESP8266 over UART. It runs since several weeks without any issues on SW V11.17.

Now i'm building a new unit with an other BMS with SW V11.262 and getting several failure messages.

![CRC_error](https://github.com/syssi/esphome-jk-bms/assets/51508965/739028ae-12b7-4b86-a948-153fa6c4b2af)

the new ESP8266 runs on my first BMS without issues.
I've allready checked the wiring, but without success.
[jk-bms-kopie.yaml.txt](https://github.com/syssi/esphome-jk-bms/files/12327939/jk-bms-kopie.yaml.txt)

any ideas, then changing to an ESP32?

Best regards
Christoph

**Comment by Blackforrestpilot** [comment]
additional info:
my "old" unit based on version 1.2.0 is running with the new BMS with SW V11.262 without any problems
This old unit was build with ESPHome 2022.4.0

regards
Christoph

**Comment by syssi** [comment]
Are you able to downgrade your ESPHome installation? Could you try component version 1.5.0 plus ESPHome 2022.4.0?

**Comment by Blackforrestpilot** [comment]
i tested on an different PC, which i've used to setup the first unit.
Python version is 3.11.0
esphome version is 2022.10.2

unfortunately i get the same result with "CRC check failed!" and "Invalid header"
![image](https://github.com/syssi/esphome-jk-bms/assets/51508965/87ac84c3-a559-4c53-aeb5-9a9195fe7fca)

I've ordered some new ESP and will test my luck with new hardware.
i will keep you informed

**Comment by Blackforrestpilot** [comment]
I am now completely confused
This afternoon I flashed the 2nd ESP8266 with the old program and connected it to my first battery with BMS (SW V11.17). There it works without any errors or abnormalities.
Then I flashed the previous ESP with the new program and connected it to the new BMS (SW V11.262).
And there it runs without any problems. No CRC or header errors.
Only sometimes there is an error message in the log that took a little too long.
![image](https://github.com/syssi/esphome-jk-bms/assets/51508965/27589738-4f5a-41e3-bb8d-99082b371efb)

Very confusing.
now that I don't know how to narrow down the cause further, I suggest closing here.

regards
Christoph

**Comment by syssi** [comment]
A CRC error every now and then is fine. Let's close this issue.

**Comment by ldiegos** [comment]
Hi, 
May I open it again?
I'm having the same problem with the JK_B2A8S20P with Hardware version V11.XW and software V11.287
I'm using:
  project:
    name: "syssi.esphome-jk-bms"
    # version: 2.0.0
    version: 1.5.0

Always i have this messages and the information is not updated:
![image](https://github.com/syssi/esphome-jk-bms/assets/29803600/853179f2-2dab-4a40-97d1-eef4ec09471a)
![image](https://github.com/syssi/esphome-jk-bms/assets/29803600/a0fe7309-2656-4854-8b21-c71135017a6e)

Only restarting the ESP8266 and a few minutes after I receive the cell state once:
![image](https://github.com/syssi/esphome-jk-bms/assets/29803600/6a7ca491-373a-4d33-adbe-9be184b17fa8)

Could you help me?
Using the BlueTooth connection the ESP8266 show everything but the connection is not stable and the JK is bipping all the time, so i want to have it connected with the UART port (GPS connector)

Kind regards
Luis.
