### ISSUE TITLE
Invalid header: 0xFF 0xFB

### ISSUE THREAD

**Issue by matziu** [syssi/esphome-jk-bms#366]
Hello!

I cant get it working by rs485.

Type: JK-B1A20S15P
Logs: https://hastebin.com/share/ugogajeqot.ruby

Anyone can help? (esp8266, lolin)

**Comment by syssi** [comment]
It looks like a grounding issue? Did you attach GND properly?

**Comment by SeByDocKy** [comment]
Seems to happen with new ESPhome release ....

**Comment by syssi** [comment]
If you have the chance please try a ESP32 instead. I guess this platform isn't affected.

**Comment by syssi** [comment]
Let's close this issue. Hopefully it's resolved.
