### ISSUE TITLE
Invalid value for "max_discharge_current" : 200.000015 (range 1.0 - 200.0)

### ISSUE THREAD

**Issue by Jalle19** [syssi/esphome-jk-bms#381]
My Home Assistant keeps complaining in the logs about this:
> Invalid value for number.jk_bms_max_discharge_current: 200.000015 (range 1.0 - 200.0)

**Comment by syssi** [comment]
I will have a look!

**Comment by Jalle19** [comment]
Seems like a classic floating point comparison issue. Not sure what the best fix would be, perhaps change the whole thing to use integers instead? I doubt anyone desperately needs to set discharge current to sub-ampere accuracy.

**Comment by syssi** [comment]
If pushed a fix which relaxes the upper limit. If the value passes the validation it should be handled/rounded properly.

**Comment by Jalle19** [comment]
Yeah I guess that works too :+1:
