### ISSUE TITLE
http_request.post and mqtt not work

### ISSUE THREAD

**Issue by rdaguerre** [syssi/esphome-jk-bms#383]
Hello, I was trying for a long time to get the mqtt to work while I was reading the jk bms via bluetooth and it did not publish the sensors. After many attempts I wanted to send it via http_request.post and I couldn't either. It gives me an error when trying to connect to the server. Now activate the UART function and the board restarts. It is a heltec lora 32 v2.
I would appreciate it if you could tell me what I could do to send the data online to the HA. greetings and thanks

**Comment by syssi** [comment]
If you are a Home Assistant user why do you prefer `mqtt` of `api`? Do you have a JK-BMS or Heltec Balancer? Which example YAML did you use? Should we discuss the BLE or UART connection variant?
