### ISSUE TITLE
does not create a utility meter assistant in HA, does not reset the utility meter

### ISSUE THREAD

**Issue by amgstone** [syssi/esphome-jk-bms#388]
does not create a utility meter assistant in HA, does not reset _the
![IMG_20231106_102627](https://github.com/syssi/esphome-jk-bms/assets/63303107/a39e41e2-0982-4b48-894f-11a19ad19efa)
![IMG_20231106_102500](https://github.com/syssi/esphome-jk-bms/assets/63303107/1f9f140a-22bb-436f-9ca2-5ae925f980cc)
_ utility meter

**Comment by syssi** [comment]
It's super important to provide a time source. Without the time the component is unable to reset the counter at midnight:

https://github.com/syssi/esphome-jk-bms/blob/main/yaml-snippets/esp32-ble-energy-dashboard.yaml#L43-L44

**Comment by amgstone** [comment]
time:
  - platform: sntp
    id: my_time
    timezone: Europe/Kiev

**Comment by syssi** [comment]
Please close this issue if it's resolved.

**Comment by amgstone** [comment]
but it doesn't work like that

**Comment by amgstone** [comment]
time:
  - platform: homeassistant
    id: my_time

now wrote like this

**Comment by syssi** [comment]
This:

```
time:
  - platform: sntp
```

receives the time from NTP servers. This retrieves the time from Home Assistant:

```
time:
  - platform: homeassistant
    id: my_time
```

Does the `bms0 charging energy today` sensor reset on midnight now?

**Comment by amgstone** [comment]
time:
  - platform: sntp
reset in 2 am

**Comment by syssi** [comment]
`timezone: Europe/Kiev` should fix this.

**Comment by amgstone** [comment]
when I type it, it stops working, does not reset the counter

**Comment by syssi** [comment]
Did you resolve the issue? I'm unable to replicate it.

**Comment by amgstone** [comment]
yes, having solved the task by flashing esp
