### ISSUE TITLE
Missing cell resistance values with UART-TTL config yaml

### ISSUE THREAD

**Issue by giangy11** [syssi/esphome-jk-bms#394]
Hi, 
I notice there are no sensors for cell resistances (and maybe a missing switch for the active balancing option and the active balance currency) in the 'esp32-example.yaml' configuration file.
Can I ask why those sensors are missing in the uart-ttl configuration but instead they are in the ble config file?

thanks in advance

![image](https://github.com/syssi/esphome-jk-bms/assets/6941069/efb4e93a-a344-4697-a29f-5359c555b62b)

**Comment by syssi** [comment]
The information isn't part of the UART-TTL protocol. The same applies to the balancing current unfortunately.

**Comment by giangy11** [comment]
ah ok didn't know, thanks anyway for the great job

**Comment by giangy11** [comment]
ah ok didn't know, thanks anyway for the great job
