### ISSUE TITLE
binary_sensor not working when having 2 ble connected  victron shunt and jk bms 

### ISSUE THREAD

**Issue by riker65** [syssi/esphome-jk-bms#395]
Hi
maybe you have an idea,

I am reading the victron shunt and the jk bms with the ESP
so mixing 2 sources,

in general I can connect to shunt and jk, but binary actions are not displayed

maybe there is a conflict with the 2 sources 
[  external_components_source_shunt: github://Fabian-Schmidt/esphome-victron_ble 
](url)

radio button for on and off balancing, charging, is not appearing.

`binary_sensor:
  - platform: jk_bms_ble
    balancing:
        #      name: "${bmsname} balancing"
      name: "1 ${bmsname} balancing"      
      id: balancing_BMS
      
    charging:
      name: "1 ${bmsname} charging"
      id: charging
    discharging:
      name: "1 ${bmsname} discharging"
      id: discharging `

Action Radio button not available

![image](https://github.com/syssi/esphome-jk-bms/assets/20332429/230a6cb3-7635-43c2-bac9-07dd5d6e602f)

maybe I need to define mot on the binary_sensor?

Thanks Thomas

**Comment by riker65** [comment]
user error, all working, forgot the switch

**Comment by adrusa** [comment]
> Hi maybe you have an idea,
> 
> I am reading the victron shunt and the jk bms with the ESP so mixing 2 sources,
> 
> in general I can connect to shunt and jk, but binary actions are not displayed
> 
> maybe there is a conflict with the 2 sources [ external_components_source_shunt: github://Fabian-Schmidt/esphome-victron_ble ](url)
> 
> radio button for on and off balancing, charging, is not appearing.
> 
> `binary_sensor:
> 
> * platform: jk_bms_ble
>   balancing:
>   #      name: "${bmsname} balancing"
>   name: "1 ${bmsname} balancing"
>   id: balancing_BMS
>   charging:
>   name: "1 ${bmsname} charging"
>   id: charging
>   discharging:
>   name: "1 ${bmsname} discharging"
>   id: discharging `
> 
> Action Radio button not available
> 
> ![image](https://private-user-images.githubusercontent.com/20332429/284360844-230a6cb3-7635-43c2-bac9-07dd5d6e602f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NDg1NDcsIm5iZiI6MTcwMDk0ODI0NywicGF0aCI6Ii8yMDMzMjQyOS8yODQzNjA4NDQtMjMwYTZjYjMtNzYzNS00M2MyLWJhYzktMDdkZDVkNmU2MDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDIxMzcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZDBlODg4YmMwOGY1NTlhMmFkMzJkNTI4ZGRmN2M0NjQyOGI5ODUzOTM4OTY2OTJhYjdhYmY3ODU2Y2I1MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wk1CaY0zC1xNQc_JGLq41aJhmlX1x1O5ewQ2FgTB2oU)
> 
> maybe I need to define mot on the binary_sensor?
> 
> Thanks Thomas

Please how did you combine 2 sources? Please share your yaml. Thanks.

**Comment by riker65** [comment]
Hi

just added 
and used components from both sources:

```
`  external_components_source_shunt: github://Fabian-Schmidt/esphome-victron_ble 
  mac_address_shunt_format: xxx 
 
  mac_address_shunt: "xxx"
 
  external_components_source_jk: github://syssi/esphome-jk-bms@main
  mac_address_bms: xx  
  protocol_version: JK02_32S
```

`does this help?
