### ISSUE TITLE
Multiple external_components_source

### ISSUE THREAD

**Issue by adrusa** [syssi/esphome-jk-bms#398]
Can I combine external_components_source? Can I for instance use a single ESP32 for both JBD and JK BSMes or JBD and Victron etc?

**Comment by syssi** [comment]
Yes. This is possible if you merge the relevant parts of both examples. What do you want to combine exactly?

**Comment by adrusa** [comment]
> Yes. This is possible if you merge the relevant parts of both examples. What do you want to combine exactly?

Thanks for your response. I'm looking to combine your JK solar and ANT BMS external components into a single ESP32 using BLE.

**Comment by syssi** [comment]
BLE in both cases?

**Comment by adrusa** [comment]
> I've attached a YAML how it should look like: [esp32-jk-ant-combined.yaml.txt](https://github.com/syssi/esphome-jk-bms/files/13473437/esp32-jk-ant-combined.yaml.txt)

This did not work. The ANT bms did not respond.

**Comment by syssi** [comment]
Did you update the MAC address? Does the BMS respond if the YAMLs aren't combined?

**Comment by adrusa** [comment]
> Did you update the MAC address? Does the BMS respond if the YAMLs aren't combined?

Yes, I updated the mac address and yes, the ANT code worked when used alone.

**Comment by syssi** [comment]
Which ESPHome version do you use?

**Comment by adrusa** [comment]
The latest version.

**Comment by syssi** [comment]
Which version exactly?

**Comment by adrusa** [comment]
> Which version exactly?

2023.11.5

**Comment by syssi** [comment]
Perfect. It's still strange that there are no multiple connections possible. In general it should work.
