### ISSUE TITLE
Add heating switch

### ISSUE THREAD

**Issue by RFDarter** [syssi/esphome-jk-bms#405]
It would be nice if you could add the heating functioniality,

**Comment by syssi** [comment]
Are you able to test the feature as soon it's available?

**Comment by RFDarter** [comment]
yep, i got a 4s pack read to test on my bench.
I also have a B2A20S20P-HC waiting to get installed once my cells arrive.

**Comment by RFDarter** [comment]
Do you have an documentaion of the jk modbus? 
All I found is this, which is from 2022 and no documentation on the heating function
http://www.jk-bms.com/Upload/2022-05-19/1621104621.pdf

This is the newes one, but i guess its the one for the new seplos stile bms
http://www.jk-bms.com/Upload/2023-11-28/1721459145.pdf

**Comment by RFDarter** [comment]
I tried to dump the complete content of data and compare it to when the heating switch is toggled and when it is not.
The dump is except for some changing cell volatages identical, so i guess they did't bother to update the modbus.
So i gess it would only work via bluethooth.

**Comment by syssi** [comment]
Could you tell me the firmware version of your BMS?

**Comment by syssi** [comment]
The `heating switch` is available now. Please extend your YAML and give it a try: https://github.com/syssi/esphome-jk-bms/blob/main/esp32-ble-v11-example.yaml#L281-L282

**Comment by RFDarter** [comment]
Hi, thanks I will give it a try tonight.
Will it work over uart and ble?

**Comment by syssi** [comment]
BLE!

**Comment by RFDarter** [comment]
I guess uart is not possible? Did you get any Informations from jk?
I havent recived an answer to my guestion about the heating Status an the uart Modbus protocol.
