### ISSUE TITLE
JK BMS Display port not transmitting data

### ISSUE THREAD

**Issue by Al1-ISSA** [syssi/esphome-jk-bms#418]
Hi,
I am trying to connect a 7inch display with a esp32s3 board to the display port of a  JK-PB2A16.
I keep receiving 00 as a response. Does any one know if the display port need a different frame format from the gps.

**Comment by syssi** [comment]
Yes. It's another protocol. See https://github.com/syssi/esphome-jk-bms/issues/118

**Comment by Al1-ISSA** [comment]
> Yes. It's another protocol. See #118

Is there a pdf for this specific protocol ? I couldn't find one online and the company wouldn't provide one.

**Comment by syssi** [comment]
I don't have any details about the protocol unfortunately.

**Comment by 23900** [comment]
display port protocol:
Communication interface UART 
level standard RS485 
Baud rate 2400bps 
Data bit 8 Stop bit 1 No parity bit

Chinese document protocol
http://www.jk-bms.com/en/Upload/2023-12-05/1556482191.pdf
