### ISSUE TITLE
problems with the latest firmware of standard jk

### ISSUE THREAD

**Issue by Thedoctor68** [syssi/esphome-jk-bms#454]
I'm having problems with one of the latest standard versions of the jk bms, it doesn't detect several values, the cell delta is wrong, the SOC is not displayed and several other errors, on the contrary the voltage of my 16 cells is displayed correctly
![BMS jk](https://github.com/syssi/esphome-jk-bms/assets/38039382/38e61419-7b01-473e-907a-c55a00438af6)

**Comment by Thedoctor68** [comment]
<img width="878" alt="Screenshot 2024-02-18 alle 17 13 08" src="https://github.com/syssi/esphome-jk-bms/assets/38039382/82e8d957-1970-4489-b779-7044fa7b9465">

I have configured this protocol

**Comment by Thedoctor68** [comment]
i have other 2 older jk-bms and all perfect, any solution?

**Comment by RFDarter** [comment]
Have you tried `protocol_version: JK02_24S` ?

**Comment by Thedoctor68** [comment]
> Have you tried `protocol_version: JK02_24S` ?

i'll try thanks

**Comment by syssi** [comment]
Did you resolve the issue? The wrong `protocol_version` is the root cause for sure.
