### ISSUE TITLE
Throw all code together for all in one device?

### ISSUE THREAD

**Issue by thitcher** [syssi/esphome-jk-bms#467]
Hi,
I have a question about the code.
I use the virtual meter for Soyosurce and now I want to use your code for my Neey and JK-BMS, too.
Virtual meter is connected via UART, the Neey and JK-BMS should be connected via BT.
In the JK-BMS code I see a setting for the correct protocol, so I´m not sure if this setting will impact the connection with the Neey if the code is merged.
Iam not very good in programming, but I will try to merge all together if this is possible.
Can you please tell me if it will be possible?

**Comment by syssi** [comment]
Yes it is possible and should work out of the box. Do you still need support?
