### ISSUE TITLE
JK-PBx - Where are the RCV Time and RFV Time params/values? BLE or RS-485

### ISSUE THREAD

**Issue by txubelaxu** [syssi/esphome-jk-bms#484]
Hi,

Somebody does know where are those values inside the status or settings frames? Somewhere else to looking for?

If not, is there anybody that could contact JK engineers to request that information?

Many thanks!!!

Txu

**Comment by txubelaxu** [comment]
Found where are. Checking if are accesible somehow via RS-485 internal network.

**Comment by syssi** [comment]
The values are available at the `device info frame` via BLE. See #549
