### ISSUE TITLE
Total Current for multiple JK BMS devices

### ISSUE THREAD

**Issue by Benthegreat** [syssi/esphome-jk-bms#490]
How would you combine two JK BMS values together?  I am using your esp32-example-multiple-devices code and two esp32-example-faker code.
Every option I have tired I get errors like not declared in scope.

**Comment by thegoloone** [comment]
I would try to add an id for the sensor I want to calculate.
```
    current:
      name: "bms1 current"
      id: bms1_current
```

And add another sensor taht calculates like
```
  - platform: template
    name: Total Current
    unit_of_measurement: "A"
    accuracy_decimals: 0
    state_class: measurement
    lambda: |-
      return (id(bms1_current).state + id(bms2_current).state);
    update_interval: 5s
    device_class: energy
```
