### ISSUE TITLE
JK-B2A24S15P Many values are 0

### ISSUE THREAD

**Issue by Selyria** [syssi/esphome-jk-bms#495]
I have the problem that yesterday I connected to my BMS with my cell phone where the values are correct a few hours later they are correct in the app but with the Esp they are wrong. Many values are 0

![WhatsApp Bild 2024-04-24 um 15 17 13_c675a85a](https://github.com/syssi/esphome-jk-bms/assets/179698/f25f64cd-f7ea-45cf-9fae-9f4a54ce69b2)

![WhatsApp Bild 2024-04-24 um 15 20 45_2468d582](https://github.com/syssi/esphome-jk-bms/assets/179698/7b7b262f-2954-4ad2-8587-337a1267ba4c)

![Unbenannt](https://github.com/syssi/esphome-jk-bms/assets/179698/068a0ae9-49a8-4321-b155-f6a519f94a9c)

**Comment by syssi** [comment]
Did you set the proper `protocol_version` at your YAML?

**Comment by Selyria** [comment]
Ich denke, auf jeden Fall ging es 8 Monate ohne Probleme, dann habe ich die ESP32 getrennt, um einen Blick mit der App zu haben und 1-2 Stunden später bemerkte ich, dass einige Daten auf 0 waren

**Comment by Selyria** [comment]
Sorry, the fault lies with me. I still had version 1.5 on it, then disconnected the power from the ESP and then looked at it with the BMS app and then reconnected the ESP to the power supply. After that the values were gone. 

I then thought that the problem was with the ESP, flashed it again with the current version 2.0 and then had the same problems with the values. However, I saw that I now have to use version JK02_32S in the protocol and had JK02 in version 1.5.

Now everything is working again thanks for the tip
