### ISSUE TITLE
ESP8266MOD 3.3V sourcing

### ISSUE THREAD

**Issue by dajpereira** [syssi/esphome-jk-bms#498]
Can I get help with the wiring diagram?

I have one ESP8266MOD and want to use it so I can read the JK 16S BMS trough wifi?

Whats is the correct wiring from bms to esp8266MOD and where can I get the 3.3V suply?

**Comment by syssi** [comment]
> Can I get help with the wiring diagram?

https://github.com/syssi/esphome-jk-bms?tab=readme-ov-file#schematics

You have to connect the BMS (GPS port) with three wires (RX, TX, GND). The safest way is to power the ESP with an external power supply (not! powered by the BMS!)

> I have one ESP8266MOD and want to use it so I can read the JK 16S BMS trough wifi?

Yes. The ESP make the measurements available via MQTT or the native `api`. Also a web interface can be enable/compiled in if you like.

> Whats is the correct wiring from bms to esp8266MOD and where can I get the 3.3V suply?

This is tricky and I cannot help here much. There a some users powering the ESP using the battery but be careful. You could also destroy your ESP or BMS: https://github.com/syssi/esphome-jk-bms/issues/287
