### ISSUE TITLE
balancer-switch for jkbms component  and resistance sensor

### ISSUE THREAD

**Issue by levgenv** [syssi/esphome-jk-bms#507]
Hi
I have JK-B1A24S15P via UART-TTL and it works fine
i want to have balancer-switch and resistance sensors for cells.

balancer-switch for jkbms component   is commented out
https://github.com/syssi/esphome-jk-bms/blob/bd52417d1cc98a201742b749a2eefd84c05278b0/components/jk_bms/switch/__init__.py#L40-L45

Else i can't add  resistance sensors for cells as in jkbms-ble

Is it a limitation of the jkbms that the balancer can not be switched on/off via UART-TLL but only via bluetooth or anything else?

**Comment by syssi** [comment]
The balancer cannot be controlled via UART-TTL. Also the cell resistance isn't available here. It can be controlled/retrieved via bluetooth only.
