### ISSUE TITLE
New JK-BMS inverter missing sensor

### ISSUE THREAD

**Issue by grydo** [syssi/esphome-jk-bms#511]
Hello in the yaml current many sensors and switches are missing.

![1](https://github.com/syssi/esphome-jk-bms/assets/133514135/bd8e3073-d85c-4d4a-bed7-1c905573c08b)
![2](https://github.com/syssi/esphome-jk-bms/assets/133514135/2799a8bd-655b-46d2-ad1f-5f77c75d5492)
![3](https://github.com/syssi/esphome-jk-bms/assets/133514135/63b1c9a7-b589-4a0c-afbf-0d3fe5fd25ad)

**Comment by testpaul999** [comment]
There we will wait for syssi to merge this branch https://github.com/syssi/esphome-jk-bms/tree/add-more-controls to the main version. At this branche the most new switches and sensors are there. :-)

regrads

**Comment by grydo** [comment]
what yaml file name?

**Comment by syssi** [comment]
This merge request introduces the new tempature sensor: https://github.com/syssi/esphome-jk-bms/pull/525

**Comment by syssi** [comment]
The device support is complete. Please re-open the issue if you still miss something!
