### ISSUE TITLE
JK PB2A16S20P (BLE) - cell_request_charge_voltage issue

### ISSUE THREAD

**Issue by MacieGx** [syssi/esphome-jk-bms#529]
Hi there 👋 
I really need the ability to control cell_request_charge_voltage from the HA and I noticed that a few days ago a [PR](https://github.com/syssi/esphome-jk-bms/pull/485) was merged that allows it.

Unfortunately, as soon as I add this to `number:` section
```
cell_request_charge_voltage:
      name: "${name} cell request charge voltage"
```
It stopped updating all editable values.
There is nothing interesting in the logs. 

<img width="382" alt="image" src="https://github.com/syssi/esphome-jk-bms/assets/32741786/9f77b5ef-b73d-4b59-8d58-34c6da7dce8f">

The set protocol is: JK02_32S. Am I doing something wrong?

**Comment by syssi** [comment]
The settings frame isn't retrieved automatically/periodically. Please pree the `retrieve settings` button to retrieve the settings. They will be applied to the entities.

**Comment by MacieGx** [comment]
You're right, I totally forgot about it. Everything works as it should. Thank you very much for your help. ❤️
