### ISSUE TITLE
Integration deye and jk BMS 

### ISSUE THREAD

**Issue by sarzyk** [syssi/esphome-jk-bms#532]
Hi is there any chance to integrate Deye RW-M6.1 battery with seccond diy battery JK BMS 2A16S20P?
I need to charge and discharge Deye battery only 80A but the diy battery (JK) over 150A. Will you board help mi with this?

**Comment by syssi** [comment]
IMO the Mosfet of the BMS shouldn't be used to cut off the charging power periodically. It's just for emergency/protection which should happen only occasionally. I therefore doubt that this project will help you. It could just provide some measurements (SoC etc.).

**Comment by sarzyk** [comment]
Ok. Thanks

**Comment by sarzyk** [comment]
But maybe it can minimize charging when is almost full (battery). Not permanently shutting down charging.
