### ISSUE TITLE
Make cell resistance sensors available for UART-TTL connections (esp8622)

### ISSUE THREAD

**Issue by Co2u** [syssi/esphome-jk-bms#536]
Can you add a sensors for esp8622 like the resistance per cell a switch on or off for balancer. All sensor like in the esp32 file please 🥺

**Comment by syssi** [comment]
That's impossible because the UART-TTL protocol doesn't provide these details and the balancer isn't controllable here. You have to use the BLE protocol & connection to retrieve these measurements.
