### ISSUE TITLE
skip_updates

### ISSUE THREAD

**Issue by hemskgren** [syssi/esphome-jk-bms#539]
Hi

I have ESP32 wroom 32 with 46 entries in HA, running BLE to the BMS, yes known to be bad on BLE.

I have run this setup for about a year (with esphome updates 2-4 times) and have notice for some time it take a-lot of time for 'non cell' related value to update, ex up to 10-30 min is not uncommon.
Do the jk-bms component have cell priority?

As I like to have all the 46 entries, but do not need them polled each time! Do it exist anything like modbus > skip_updates? 
https://esphome.io/components/sensor/modbus_controller.html

I can/want to skip poll/update ex all my 16s cell, temperature  etc on each second update! Is this possible?

Was running 2024.5.0  and now 2024.7.0 with latest jk-bms component, no big difference.

**Comment by syssi** [comment]
It looks like there is an important detail you aren't aware of: The BMS publishs a single frame (called `cell info frame`) as BLE notification twice per second. All sensor values are included here. You can use the `throttle` option do discard most of the incoming data. There is no polling of individual measurements.
