### ISSUE TITLE
JK-PB2A16S20P: Incorrect SOC100% Voltage Range 0.003 - 1.0 Instead of 3.x - 3.65

### ISSUE THREAD

**Issue by dmode9000** [syssi/esphome-jk-bms#540]
JK-PB2A16S20P.
The allowed range for the SOC100% voltage parameter is incorrect, and the parameter change does not occur.
Error message example: "Value 3.451 for number.bms1_cell_soc100_voltage is outside valid range 0.003 - 1.0."

**Comment by syssi** [comment]
I've pushed a fix. Please recompile & flash your ESP and give it a try!

**Comment by dmode9000** [comment]
Thank you, it works fine after recompilation.
