### ISSUE TITLE
Soc 0 / Soc 100 limits in dashboard settings

### ISSUE THREAD

**Issue by holle75** [syssi/esphome-jk-bms#544]
Hi, i realized today when trying to set Soc 0 on the dashboard that limits (soc 0 / Soc 100) are wrong (upper limit 1,000). 

![jkbms_soc0](https://github.com/user-attachments/assets/1a10a712-ce14-4019-9744-82b9916af835)

So when touching those, you can´t go back to somewhere near the original setting made through the app.

**Comment by syssi** [comment]
I've fixed this issue recently here #541 

Please just flash your ESP another time. ESPHome will retrieve the most recent version of the implementation automatically.

**Comment by holle75** [comment]
thanks
