### ISSUE TITLE
JK-PB2A16S20P: constant heating on/off switching

### ISSUE THREAD

**Issue by dmode9000** [syssi/esphome-jk-bms#552]
The heating option on BMS is constantly turning off and on.

![image](https://github.com/user-attachments/assets/87c6f3a1-ca2f-43c5-b7f3-f2bc3cace454)

**Comment by syssi** [comment]
Do you have a heating element attached? Are you able to test the feature as soon it's fixed?

**Comment by syssi** [comment]
I've pushed a fix into the feature branch `heating-v14`. Please change this line at your YAML configuration to use this branch:

```
substitutions:
  # ...
  external_components_source: github://syssi/esphome-jk-bms@heating-v14
```

Recompile & flash your ESP. Does the binary sensor indicate the truth now?

**Comment by dmode9000** [comment]
> Do you have a heating element attached?

No, never was.


> Recompile & flash your ESP.

No constant heating switching now.


> Does the binary sensor indicate the truth now?

Looks like fixed.
![image](https://github.com/user-attachments/assets/58b7eaeb-5bcd-4f73-82cc-efb11ea3aed4)

**Comment by syssi** [comment]
What happens if you use the `heating switch` to turn heating on?

**Comment by signaleye** [comment]
Sorry @dmode9000 

I have same BMS and want to connect to it but no luck.. do. you have the complete yaml code to share?

**Comment by syssi** [comment]
@signaleye Could you create a new issue and provide an ESPHome log?

**Comment by dmode9000** [comment]
> What happens if you use the `heating switch` to turn heating on?

When the "heating switch" is pressed, it changes its status to pressed and remains in that state. The logs show that the heating button was pressed.



> I have same BMS and want to connect to it but no luck.. do. you have the complete yaml code to share?

https://pastebin.com/gcDZYznW#google_vignette
