### ISSUE TITLE
JK B2A24S20P voltage error and JK02 option missing

### ISSUE THREAD

**Issue by Ghilm1986** [syssi/esphome-jk-bms#591]
Hi, I was using your jk project since the last year, compiled the file with JK02 option into the hw version.
Because i changed the ssid I needed to modify the file, but when I tried to save it I had an error about JK02 unkown value when i was creating the bin file.
I suddenly tried the other option about jk02_32s but I had completely wrong voltages.
My hw version is 10.0.
![Screenshot_2024-09-04-21-04-35-51_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/f16e6a0d-d1ee-4e6c-8aa7-277483dd99a8)
![Screenshot_2024-09-04-21-21-08-61_bd59be8c3f820c1e3d6fc2892aab342d](https://github.com/user-attachments/assets/24067b82-92ac-4d97-8349-995b321f5122)
The voltages are wrong but the bms is working perfectly if i use its app.

**Comment by syssi** [comment]
Please  use `JK02_24S`.

**Comment by Ghilm1986** [comment]
Perfect..it works now.thanks a lot
