### ISSUE TITLE
Current calibration field always same value

### ISSUE THREAD

**Issue by mevlutsenol** [syssi/esphome-jk-bms#604]
Hi,

I have JK_B1A24S15P. But current calibration field always same value.

![image](https://github.com/user-attachments/assets/a148c28b-f93a-4551-b0b2-b089bcd4810e)

![image](https://github.com/user-attachments/assets/a085b84a-7359-446e-813a-6d1835198911)

**Comment by syssi** [comment]
There is not much known about the current calibration of the JK-BMS. What do you expect here? Do you know in detail how to calibrate the BMS?

**Comment by mevlutsenol** [comment]
In bluetooth application, this field shown current balance.

![image](https://github.com/user-attachments/assets/56453338-4ff2-491d-ad71-8472d1aaff3e)

**Comment by syssi** [comment]
It looks like you are mixing things up here. Are you are of the `balancing_current`?

 https://github.com/syssi/esphome-jk-bms/blob/main/esp32-ble-example.yaml#L307-L308

There is a difference between `current calibration` and the `balancing current`.

**Comment by syssi** [comment]
No. The UART-TTL protocol doesnt provide this measurement. It's available via BLE only.
