### ISSUE TITLE
JK-B2A20S20P HW V11.XA SW V11.51 is supporting?

### ISSUE THREAD

**Issue by petervpn18** [syssi/esphome-jk-bms#607]
Hi, friends! JK-B2A20S20P HW V11.XA SW V11.51 is supporting can' connect via BLE? 
BMS connected via BlueTooth

nodemcu-32s

Thanks in advance!

**Comment by syssi** [comment]
Yes. The BMS is supported and can be controlled using this project via BLE.

**Comment by petervpn18** [comment]
config nodemcu-32s
please send me.

**Comment by syssi** [comment]
Please use thie YAML configuration: https://github.com/syssi/esphome-jk-bms/blob/main/esp32-ble-v11-example.yaml

Don't miss to update the `mac_address` to the one of your device!
