### ISSUE TITLE
Display protocol doesn't return cell voltages data

### ISSUE THREAD

**Issue by bearpawmaxim** [syssi/esphome-jk-bms#611]
Hello!
Using your `jk_bms_display` component to read data from display port of my B2A20S24P bms (because gps port isn't working...).
All the values are read correctly except the `min_cell_voltage` and `max_cell_voltage`.

Here's the logs
[logs_battery-status-display_logs.txt](https://github.com/user-attachments/files/17356341/logs_battery-status-display_logs.txt)

Config can be seen at https://github.com/bearpawmaxim/esphome-configs/blob/master/battery-status-display/jkbms-display-port.yaml

**Comment by syssi** [comment]
I've merged a fixed. Please recompile your setup and give it another try!

**Comment by bearpawmaxim** [comment]
It works now! Thanks!
![20241013_210017](https://github.com/user-attachments/assets/4f76c75a-e069-4980-8dd0-9dc25866b016)

**Comment by syssi** [comment]
Nice!
