### ISSUE TITLE
Extend the modbus example

### ISSUE THREAD

**Issue by manuelmarin1967** [syssi/esphome-jk-bms#615]
hello is it possible to get the modbus protocol of the new jk pb, especially the addresses of the battery voltage, current, soc, battery capacity and all the other addresses that are missing in the yaml, as there are only the addresses of the individual voltages of the cells and the resistors of each one.
It would be a great help as I want to continue to expand my yaml with the rest of the missing addresses.
If you could post the complete addressing protocol it would be ideal for me.
Thanks in advance and keep up the great work you are doing.

**Comment by syssi** [comment]
These are all details I'm aware of: https://github.com/syssi/esphome-jk-bms/tree/main/docs/pb2a16s20p

If you make some progress please share your enhancements!

**Comment by bearpawmaxim** [comment]
Hello @syssi !
I have more complete example here
https://github.com/bearpawmaxim/esphome-configs/blob/master/battery-controller/jkbms-modbus.yaml
