### ISSUE TITLE
Duplicate key "wifi_ssid"

### ISSUE THREAD

**Issue by italodl** [syssi/esphome-jk-bms#617]
hi, i have this error  when compile  esp32-ble-example.yaml. i have changed only the mac address of my bms

Duplicate key "wifi_ssid"
  in "/config/esphome/secrets.yaml", line 6, column 1
NOTE: Previous declaration here:
  in "/config/esphome/secrets.yaml", line 2, column 1

**Comment by syssi** [comment]
Please take look at the `secrets.yaml`. The errors reports the key `wifi_ssid` exists two times here. Each key must be unique.

**Comment by italodl** [comment]
Thanks, i have cancelled one of two entry e now it work perfectly
