### ISSUE TITLE
Update to HA 2024.10.4 - update of SOME values is not working

### ISSUE THREAD

**Issue by piknew** [syssi/esphome-jk-bms#621]
Firstly - I thought the issue is ESPHome one, so I have reported: https://github.com/esphome/issues/issues/6385

But... I have noticed that for example "cell voltages" in HA are reported "live". The changes on current, power (outgoing or incoming to battery) - not (I am not sure if there are more sensors like this).

It is difficult to show it but:

**Initial state, battery is charging:**
**Notice, that voltages are ~3.32 (which confirms "charge")**
![Screenshot_1](https://github.com/user-attachments/assets/32706a4a-1dd3-4eaf-ad1a-6bbb57cebfd4)

**Battery is discharging (by reading BMS it is about -6Amp)**
**Notice, that voltages are ~3.26 (which confirms "discharge")**
![Screenshot_2](https://github.com/user-attachments/assets/7aebfaa4-d82b-4ebf-beb1-7bd698cdb46c)

**Switch again the charging - current is about +0.7 A** (please see that it is still 0.53A on HA)
![Screenshot_3](https://github.com/user-attachments/assets/266c2922-8a78-4fa7-a1db-04a197177eae)

**State - that voltages are updated immediately ("now")**
![Screenshot_5](https://github.com/user-attachments/assets/a70ac562-1bb8-4c72-9d66-977bfd842e22)

**State - that current is not updated (14 minutes ago?)**
![Screenshot_6](https://github.com/user-attachments/assets/ab86c536-b5c8-47b2-b351-f6302a92abb9)

**Comment by piknew** [comment]
It is very strange. I see that logs on "web_server" contain entries about current and power but logs on console (run just after eg. ota - do not):

Web:
![image](https://github.com/user-attachments/assets/db9a53a4-195b-4a7e-8291-24cec1efa9ea)

**Comment by syssi** [comment]
Do you use the `api` component to pass states to HA?

**Comment by syssi** [comment]
This is the root cause probably: https://github.com/esphome/esphome/pull/7321

**Comment by piknew** [comment]
> Do you use the `api` component to pass states to HA?

Yes, my yaml is provided in linked issue https://github.com/esphome/issues/issues/6385

> And this is probably a mitigation: [esphome/esphome#7547](https://github.com/esphome/esphome/pull/7547)

If I understand correctly - this shall/will be introduced to code? Simply - I need to wait for esphome fix? Or revert to HA 2024.10.3...

**Comment by piknew** [comment]
FYI - when switched to VERY_VERBOSE logging level I have noticed "Cannot send message because of TCP buffer space".

Also please notice something - this is the beginning of transmission. Last "successful" part is pair of (I have reviewed your code, so more or less I know what is happening):

[19:22:38][V][sensor:043]: 'Cell 5 Voltage': Received new state 3.358000
[19:22:38][D][sensor:094]: 'Cell 5 Voltage': Sending state 3.35800 V with 3 decimals of accuracy

But then we have only 1 line of:
[19:22:38][V][sensor:043]: 'Total Voltage': Received new state 26.859999

And there is NO following message about "Sending state". Instead there is new frame received from UART/modbus. Is it interrupting everything? I am not sure if the code is multi-threaded or interrupted (by eg. IRQ of UART?)?


![image](https://github.com/user-attachments/assets/de5d3a5d-4103-43f2-8929-19a55bb34222)

**Comment by syssi** [comment]
If you don't think the `api` component is the root cause please try the `mqtt` component instead. You will see it will resolve the issue and all states are passed to HA without any loss.

**Comment by piknew** [comment]
Ok, thanks, I will try it - never used MQTT before, so I need to learn :) Next info will be for MQTT setup.

BTW. To conclude - my setup is:
JK-BD4A8S4P

Screen is connected to dedicated BMS port. ESP32 connected to UART (as suggested on your README file).

Is it possible that one frame is coming as a result of "request" frame and the other is for display?

**Comment by syssi** [comment]
I don't know. The preamble of a display frame is 0xA5 0x5A normally.

**Comment by piknew** [comment]
With MQTT - everything seems to be OK (I am on "testing phase", so this may not be 100% valid statement).

> I don't know. The preamble of a display frame is 0xA5 0x5A normally.

Or (for this one I was not looking at the code) - may it be some more data read in next loop? I mean - please see 0xA8 0xFF ... 0xA9 ... (this one seems as to be next part or first packet). Event, if it is not used - this data somehow is read later. This is what I mean:

![image](https://github.com/user-attachments/assets/ccd43ac7-aeb3-4dee-b03d-d7697d20fb80)

**Comment by syssi** [comment]
I understand your concern now. The UART debug logger cannot simply print log messages longer as ~150 bytes. A JK-BMS UART-TTL frame is 300 bytes long. It's just printed in two parts to the log.

**Comment by piknew** [comment]
Ok, thank you for explanation. I believe this issue may be closed (I have "solved" my problem with switching to MQTT). However, the problem with HA API as I understand, is traced separately?

BTW. These pull requests have underlying issues reported (it would be good idea to link it)?

**Comment by syssi** [comment]
I think your issue at the ESPHome project is a good start to proceed. I've created the pull request in the past to make the traffic loss more obvious. At the moment it's too silent and hard to track down. I don't have the skills to resolve the issue. It's a ESPHome core issue for sure and cannot be resolved here.
