### ISSUE TITLE
JK-BMS UART Missing Functions

### ISSUE THREAD

**Issue by piknew** [syssi/esphome-jk-bms#625]
I am not sure if this is related to lack of features in UART protocol or esphome-jk-bms issue.

I would like to ask for following (for UART):

1. Make sensor "balancing_switch" as switch (not binary sensor).
2. (these exist in BLE, but not in UART): cell_resistance_1 ... cell_resistance_N

Other sensors/switches - are not important for me, so I am not mentioning these.

**Comment by syssi** [comment]
The UART-TTL protocol doesn't provide these measurements/features unfortunately.
