### ISSUE TITLE
New `JK-B2A8S20P HW: V11A SW: V11.54` not working from `GPS UART-TTL` port

### ISSUE THREAD

**Issue by Sleeper85** [syssi/esphome-jk-bms#629]
Hi @syssi,

I have next to me two BMS `JK-B2A8S20P`, the first one works well **(HW: V11.XW SW: V11.37)** but the second one with a different architecture (new?) does not work **(HW: V11A SW: V11.54)**.

There is a `UART` menu that allows you to choose between several protocols but none of them work.

The default address of the device is `1` I changed it to `0` like on the other BMS that works but it does not change anything.

I specify that it is a new BMS but **not the JK-PB inverter BMS**.

Here are some pictures of the options in the JK app.

![image](https://github.com/user-attachments/assets/90ee7cae-c65c-4371-b6f2-8e66503d844a)
![image](https://github.com/user-attachments/assets/480061a3-01d5-48d7-a9b0-bc2dcc8849c9)
![image](https://github.com/user-attachments/assets/eae3709c-81a8-4ad1-8fcf-6c05101c9eec)
![image](https://github.com/user-attachments/assets/50657d1a-4e07-4360-b06a-24bb9628d40e)

**Comment by Sleeper85** [comment]
Should I really open the BMS?

![JK-B2A8S20P V11A 1 800](https://github.com/user-attachments/assets/83beae51-8546-41ca-858e-b7f48768693b)
![JK-B2A8S20P V11A 2 800](https://github.com/user-attachments/assets/34bafbf5-3b78-42ce-aeb4-5f54a69628e1)
![JK-B2A8S20P V11A 3 800](https://github.com/user-attachments/assets/a701be43-c5aa-497b-ad23-61aa67831a31)

**Comment by syssi** [comment]
I don't want to encourage you to void the warranty. ;-) Don't break the seal.

**Comment by Sleeper85** [comment]
![HW V11 XW vs V11A](https://github.com/user-attachments/assets/433513bd-ceac-4fa1-a004-a908f16ffb8b)

**Comment by Sleeper85** [comment]
The software also behaves differently in the same way as the JK-PB series.

* OVPR should be `<` than SOC 100%
* UVPR should be `>` than SOC 0%

This seems logical but it is different from `V11.37` anyway.

![OVPR_UVPR](https://github.com/user-attachments/assets/9ee9c738-f890-4ffd-8818-0131fca315f7)

**Comment by Sleeper85** [comment]
[I will try to read the info from the display port](https://github.com/syssi/esphome-jk-bms/blob/main/esp32-display-example.yaml]

**Comment by Sleeper85** [comment]
[Looks like this issue](https://github.com/Louisvdw/dbus-serialbattery/issues/1045)

**Comment by Sleeper85** [comment]
@syssi I can retrieve the info from the RS485 display port.

**Comment by Sleeper85** [comment]
After testing the display port, I did a second try from the `GPS` port and it works now.

I don't know what happened, was it a bad contact on my prototype...

Clarification:

The UART protocol used is **000 - 4G-GPS**
Device Addr. can be **0** or **1** (default) it has no effect in this case

So you can add this new **HW: V11A** and **SW: V11.54** to the list of supported BMS.

**Comment by JohanAlvedal** [comment]
I have the same HW and can't get it to work via Bluetooth — is it not supported?
