### ISSUE TITLE
Expected behaviour of successful flash

### ISSUE THREAD

**Issue by spoonwzd** [syssi/esphome-jk-bms#67]
Can you verify the expected behaviour of a successful flash?

Looking at the log output after reboot it seems to be establishing a configuration then saving it to flash.

![image](https://user-images.githubusercontent.com/6536570/162565467-838cfb03-f9a4-425d-9f97-bc614c4255dd.png)

Is it normal to take ~3 minutes after establishing the sensor config to save preferences to flash?

Once the saving preferences to flash message appears, is it safe to power off the device at this point?

Does the ESP32 device need to be connected to the BMS when it's adding sensors on first boot?

Apologies for the noob questions, I'm still waiting for it to click for me :)

**Comment by syssi** [comment]
> Is it normal to take ~3 minutes after establishing the sensor config to save preferences to flash?

This is normal. If the startup doesn't succeed multiple times (= the boot loop counter exceeds `10`: https://esphome.io/components/ota.html) the ESPHome node goes into a recovery mode. So you are able to reflash the device via OTA.

> Once the saving preferences to flash message appears, is it safe to power off the device at this point?

It's always safe to reboot the ESP. If you reset/reboot the ESP manually 10 times in a row the recovery mode kicks in (see above).

> Does the ESP32 device need to be connected to the BMS when it's adding sensors on first boot?

No it doesn't need to be connected. The custom component polls the BMS (with a single request) periodically. The BMS responds with a full status report. You can decide by adding sensors how much data of the status report is published as sensor data.

**Comment by syssi** [comment]
Could you provide the BMS type + hardware & software version you are using? I would like to extend the list of supported devices if your device version is missing.

**Comment by spoonwzd** [comment]
Model: JK-BD6A24S10P
Hardware: 8.X
Software: 8.0.6G
Version: 3.7.1

This doesn't seem to be on your supported list and may explain why I'm not seeing any data. :/

**Comment by syssi** [comment]
It should be supported because the device pretty new. Could you provide a photo of your wiring?

**Comment by spoonwzd** [comment]
![image](https://user-images.githubusercontent.com/6536570/162567509-dd4e9ef3-7167-410a-b0da-b9ff70fdd634.png)

**Comment by syssi** [comment]
Are you sure the green cable is connected to GND? It looks like `GPIO20`.

**Comment by spoonwzd** [comment]
![image](https://user-images.githubusercontent.com/6536570/162568224-f410af8d-58e2-4dc5-bd0e-e43ce28149b5.png)

**Comment by spoonwzd** [comment]
![20220409_113449](https://user-images.githubusercontent.com/6536570/162568306-dc017a24-f866-4d59-8ade-6ab10f15f9aa.jpg)

**Comment by syssi** [comment]
Alright! Did you try to swap RX and TX just for testing? Your setup looks fine. The BMS is up and running (blinks)?

**Comment by spoonwzd** [comment]
Not tried swapping, but I can if you think it's worth a try.

BMS defo up and running.

**Comment by syssi** [comment]
Where did you buy the BMS?

**Comment by syssi** [comment]
It's worth a try!

**Comment by spoonwzd** [comment]
> Where did you buy the BMS?

https://www.aliexpress.com/store/911303103

**Comment by syssi** [comment]
No luck?

**Comment by spoonwzd** [comment]
Right, so swapping the TX/RX GPIO around didn't help.

Swapped them back to their original states and ran the debug.

![image](https://user-images.githubusercontent.com/6536570/162573372-fbe24a50-a205-4c3a-8c8d-7c8f6698530d.png)

I'm clearly getting data from the BMS but I'm not seeing anything at the MQTT listener.

I'm not running HomeAssistant - I'm using the MQTT listener in node-red which I've used before successfully.

Should I be seeing MQTT related messages in the debug output? Because I'm not!

**Comment by syssi** [comment]
Perfect! You are able to retrieve the data from the BMS. The next step is to debug the MQTT connection. I don't know node-red in details. Is there a mosquitto broker or something like that? Could you take a look at the mosquitto.log? Is the ESPHome able to connect? Gets the connection dropped/disconnected because of failed authorization or something?

**Comment by spoonwzd** [comment]
Using MQTT explorer I can connect to my MQTT broker and see all the data flowing in, so this must be something throwing me off in node-red.

![image](https://user-images.githubusercontent.com/6536570/162574571-d32d132b-602f-488a-b7ee-c6ad70fc41c5.png)

I'll suss it, but pretty sure your bit is all working great now.

Thanks for all your help.

**Comment by spoonwzd** [comment]
Ok I was subscribing to:

`batt3/sensor/batt3_cell_voltage_1`

instead of

`batt3/sensor/batt3_cell_voltage_1/state`

#facepalm
